-- 040 (following Run A tenant identity039): additive shared incident/dispatch and operational fleet.
-- Approved Human decisions and linked source facts remain distinct.

CREATE TABLE operation_incidents (
	incident_id UUID DEFAULT gen_random_uuid() NOT NULL,
	kind VARCHAR(30) NOT NULL,
	title VARCHAR(500) NOT NULL,
	occurred_at TIMESTAMP WITH TIME ZONE,
	address TEXT,
	number VARCHAR(120),
	emergency_case_id UUID,
	fire_investigation_case_id UUID,
	status VARCHAR(20) DEFAULT 'active' NOT NULL,
	notes TEXT,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (incident_id),
	CONSTRAINT ck_incident_kind CHECK (kind IN ('fire','rescue','emergency_support','watch','storm','other')),
	CONSTRAINT ck_incident_single_source CHECK (NOT (emergency_case_id IS NOT NULL AND fire_investigation_case_id IS NOT NULL)),
	CONSTRAINT ck_incident_no_source_copy CHECK ((emergency_case_id IS NULL AND fire_investigation_case_id IS NULL) OR (occurred_at IS NULL AND address IS NULL AND number IS NULL)),
	CONSTRAINT ck_incident_emergency_kind CHECK (emergency_case_id IS NULL OR kind = 'emergency_support'),
	CONSTRAINT ck_incident_fire_kind CHECK (fire_investigation_case_id IS NULL OR kind = 'fire'),
	CONSTRAINT ck_incident_status CHECK (status IN ('active','cancelled')),
	UNIQUE (emergency_case_id),
	FOREIGN KEY(emergency_case_id) REFERENCES emergency_cases (emergency_case_id),
	UNIQUE (fire_investigation_case_id),
	FOREIGN KEY(fire_investigation_case_id) REFERENCES fire_investigation_cases (fire_investigation_case_id)
);

CREATE TABLE operation_vehicles (
	vehicle_id UUID DEFAULT gen_random_uuid() NOT NULL,
	code VARCHAR(100) NOT NULL,
	name VARCHAR(200) NOT NULL,
	registration VARCHAR(100),
	active BOOLEAN DEFAULT true NOT NULL,
	odometer NUMERIC(14, 1) DEFAULT 0 NOT NULL,
	fuel_stock NUMERIC(14, 2) DEFAULT 0 NOT NULL,
	next_inspection_on DATE,
	next_service_on DATE,
	next_service_odometer NUMERIC(14, 1),
	notes TEXT,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (vehicle_id),
	CONSTRAINT ck_vehicle_nonnegative CHECK (odometer >= 0 AND fuel_stock >= 0),
	CONSTRAINT ck_vehicle_service_odometer CHECK (next_service_odometer IS NULL OR next_service_odometer >= 0),
	UNIQUE (code)
);

CREATE TABLE operation_allowance_rates (
	rate_id UUID DEFAULT gen_random_uuid() NOT NULL,
	code VARCHAR(100) NOT NULL,
	label VARCHAR(300) NOT NULL,
	amount NUMERIC(14, 2) NOT NULL,
	basis VARCHAR(30) NOT NULL,
	rounding VARCHAR(20) NOT NULL,
	approval_reference TEXT NOT NULL,
	status VARCHAR(20) DEFAULT 'draft' NOT NULL,
	approved_by UUID,
	approved_at TIMESTAMP WITH TIME ZONE,
	approval_note TEXT,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (rate_id),
	CONSTRAINT ck_rate_rounding CHECK (rounding IN ('half_up','half_even','down')),
	CONSTRAINT ck_rate_amount CHECK (amount >= 0),
	CONSTRAINT ck_rate_basis CHECK (basis IN ('per_dispatch','per_crew','per_hour')),
	CONSTRAINT ck_rate_status CHECK (status IN ('draft','approved')),
	CONSTRAINT ck_rate_human CHECK (status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)),
	UNIQUE (code),
	FOREIGN KEY(approved_by) REFERENCES app_users (user_id)
);

CREATE TABLE operation_dispatches (
	dispatch_id UUID DEFAULT gen_random_uuid() NOT NULL,
	incident_id UUID NOT NULL,
	unit VARCHAR(200) NOT NULL,
	vehicle_id UUID,
	departed_at TIMESTAMP WITH TIME ZONE,
	arrived_at TIMESTAMP WITH TIME ZONE,
	returned_at TIMESTAMP WITH TIME ZONE,
	activity TEXT,
	report TEXT,
	document_id UUID,
	status VARCHAR(20) DEFAULT 'draft' NOT NULL,
	rate_id UUID,
	candidate_amount NUMERIC(14, 2),
	calculation JSON DEFAULT '{}'::json NOT NULL,
	official_amount NUMERIC(14, 2),
	reviewed_by UUID,
	reviewed_at TIMESTAMP WITH TIME ZONE,
	approved_by UUID,
	approved_at TIMESTAMP WITH TIME ZONE,
	review_snapshot JSON DEFAULT '{}'::json NOT NULL,
	review_note TEXT,
	cancellation_note TEXT,
	cancelled_by UUID,
	cancelled_at TIMESTAMP WITH TIME ZONE,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (dispatch_id),
	CONSTRAINT uq_dispatch_vehicle UNIQUE (dispatch_id, vehicle_id),
	CONSTRAINT ck_dispatch_status CHECK (status IN ('draft','reviewed','approved','cancelled')),
	CONSTRAINT ck_dispatch_candidate CHECK (candidate_amount IS NULL OR candidate_amount >= 0),
	CONSTRAINT ck_dispatch_official CHECK (official_amount IS NULL OR official_amount >= 0),
	CONSTRAINT ck_dispatch_official_gate CHECK (official_amount IS NULL OR (status IN ('approved','cancelled') AND approved_by IS NOT NULL)),
	CONSTRAINT ck_dispatch_human CHECK (status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND reviewed_by IS NOT NULL)),
	CONSTRAINT ck_dispatch_return CHECK (returned_at IS NULL OR (departed_at IS NOT NULL AND returned_at >= departed_at)),
	CONSTRAINT ck_dispatch_arrival CHECK (arrived_at IS NULL OR (departed_at IS NOT NULL AND arrived_at >= departed_at AND (returned_at IS NULL OR arrived_at <= returned_at))),
	FOREIGN KEY(incident_id) REFERENCES operation_incidents (incident_id),
	FOREIGN KEY(vehicle_id) REFERENCES operation_vehicles (vehicle_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id),
	FOREIGN KEY(rate_id) REFERENCES operation_allowance_rates (rate_id),
	FOREIGN KEY(reviewed_by) REFERENCES app_users (user_id),
	FOREIGN KEY(approved_by) REFERENCES app_users (user_id),
	FOREIGN KEY(cancelled_by) REFERENCES app_users (user_id)
);

CREATE INDEX ix_operation_dispatches_incident_id ON operation_dispatches (incident_id);

CREATE TABLE operation_dispatch_crew (
	crew_id UUID DEFAULT gen_random_uuid() NOT NULL,
	dispatch_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	role VARCHAR(100) NOT NULL,
	PRIMARY KEY (crew_id),
	CONSTRAINT uq_dispatch_employee UNIQUE (dispatch_id, employee_id),
	FOREIGN KEY(dispatch_id) REFERENCES operation_dispatches (dispatch_id),
	FOREIGN KEY(employee_id) REFERENCES employees (employee_id)
);

CREATE INDEX ix_operation_dispatch_crew_dispatch_id ON operation_dispatch_crew (dispatch_id);

CREATE TABLE operation_vehicle_trips (
	trip_id UUID DEFAULT gen_random_uuid() NOT NULL,
	vehicle_id UUID NOT NULL,
	dispatch_id UUID,
	driver_employee_id UUID,
	started_at TIMESTAMP WITH TIME ZONE NOT NULL,
	ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
	start_odometer NUMERIC(14, 1) NOT NULL,
	end_odometer NUMERIC(14, 1) NOT NULL,
	purpose TEXT NOT NULL,
	created_by UUID NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	document_id UUID,
	PRIMARY KEY (trip_id),
	CONSTRAINT fk_trip_dispatch_vehicle FOREIGN KEY(dispatch_id, vehicle_id) REFERENCES operation_dispatches (dispatch_id, vehicle_id),
	CONSTRAINT ck_trip_mileage CHECK (end_odometer >= start_odometer AND start_odometer >= 0),
	CONSTRAINT ck_trip_times CHECK (ended_at >= started_at),
	CONSTRAINT uq_trip_start UNIQUE (vehicle_id, started_at),
	FOREIGN KEY(vehicle_id) REFERENCES operation_vehicles (vehicle_id),
	FOREIGN KEY(dispatch_id) REFERENCES operation_dispatches (dispatch_id),
	FOREIGN KEY(driver_employee_id) REFERENCES employees (employee_id),
	FOREIGN KEY(created_by) REFERENCES app_users (user_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id)
);

CREATE INDEX ix_operation_vehicle_trips_vehicle_id ON operation_vehicle_trips (vehicle_id);

CREATE TABLE operation_fuel_entries (
	fuel_id UUID DEFAULT gen_random_uuid() NOT NULL,
	vehicle_id UUID NOT NULL,
	kind VARCHAR(20) NOT NULL,
	liters NUMERIC(14, 2) NOT NULL,
	amount NUMERIC(14, 2) NOT NULL,
	occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
	notes TEXT,
	created_by UUID NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	document_id UUID,
	PRIMARY KEY (fuel_id),
	CONSTRAINT ck_fuel_kind CHECK (kind IN ('receipt','issue','refuel')),
	CONSTRAINT ck_fuel_amount CHECK (liters > 0 AND amount >= 0),
	FOREIGN KEY(vehicle_id) REFERENCES operation_vehicles (vehicle_id),
	FOREIGN KEY(created_by) REFERENCES app_users (user_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id)
);

CREATE INDEX ix_operation_fuel_entries_vehicle_id ON operation_fuel_entries (vehicle_id);

CREATE TABLE operation_vehicle_services (
	service_id UUID DEFAULT gen_random_uuid() NOT NULL,
	vehicle_id UUID NOT NULL,
	kind VARCHAR(30) NOT NULL,
	performed_on DATE NOT NULL,
	description TEXT NOT NULL,
	cost NUMERIC(14, 2) DEFAULT 0 NOT NULL,
	next_inspection_on DATE,
	next_service_on DATE,
	next_service_odometer NUMERIC(14, 1),
	status VARCHAR(20) DEFAULT 'draft' NOT NULL,
	reviewed_by UUID,
	approved_by UUID,
	approved_at TIMESTAMP WITH TIME ZONE,
	review_note TEXT,
	resolves_fault_id UUID,
	resolved_by_service_id UUID,
	resolved_at TIMESTAMP WITH TIME ZONE,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	created_by UUID NOT NULL,
	document_id UUID,
	PRIMARY KEY (service_id),
	CONSTRAINT uq_service_vehicle UNIQUE (service_id, vehicle_id),
	CONSTRAINT fk_repair_fault_vehicle FOREIGN KEY(resolves_fault_id, vehicle_id) REFERENCES operation_vehicle_services (service_id, vehicle_id),
	CONSTRAINT fk_fault_repair_vehicle FOREIGN KEY(resolved_by_service_id, vehicle_id) REFERENCES operation_vehicle_services (service_id, vehicle_id),
	CONSTRAINT ck_repair_fault_link CHECK (resolves_fault_id IS NULL OR (kind = 'repair' AND resolves_fault_id <> service_id)),
	CONSTRAINT ck_fault_resolution CHECK (resolved_by_service_id IS NULL OR (kind = 'fault' AND resolved_by_service_id <> service_id AND resolved_at IS NOT NULL)),
	CONSTRAINT ck_service_kind CHECK (kind IN ('inspection','vehicle_inspection','repair','fault','service')),
	CONSTRAINT ck_service_cost CHECK (cost >= 0),
	CONSTRAINT ck_service_odometer CHECK (next_service_odometer IS NULL OR next_service_odometer >= 0),
	CONSTRAINT ck_service_inspection_date CHECK (next_inspection_on IS NULL OR next_inspection_on >= performed_on),
	CONSTRAINT ck_service_service_date CHECK (next_service_on IS NULL OR next_service_on >= performed_on),
	CONSTRAINT ck_service_status CHECK (status IN ('draft','reviewed','approved','cancelled')),
	CONSTRAINT ck_service_human CHECK (status <> 'approved' OR (reviewed_by IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL)),
	FOREIGN KEY(vehicle_id) REFERENCES operation_vehicles (vehicle_id),
	FOREIGN KEY(reviewed_by) REFERENCES app_users (user_id),
	FOREIGN KEY(approved_by) REFERENCES app_users (user_id),
	FOREIGN KEY(resolves_fault_id) REFERENCES operation_vehicle_services (service_id),
	FOREIGN KEY(resolved_by_service_id) REFERENCES operation_vehicle_services (service_id),
	FOREIGN KEY(created_by) REFERENCES app_users (user_id),
	FOREIGN KEY(document_id) REFERENCES documents (document_id)
);

CREATE INDEX ix_operation_vehicle_services_vehicle_id ON operation_vehicle_services (vehicle_id);

CREATE TABLE operation_import_previews (
	preview_id UUID DEFAULT gen_random_uuid() NOT NULL,
	dataset VARCHAR(30) NOT NULL,
	filename TEXT NOT NULL,
	file_sha256 VARCHAR(64) NOT NULL,
	row_data JSON NOT NULL,
	created_by UUID NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	status VARCHAR(20) DEFAULT 'preview' NOT NULL,
	applied_ids JSON DEFAULT '[]'::json NOT NULL,
	version BIGINT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (preview_id),
	CONSTRAINT ck_import_status CHECK (status IN ('preview','applied')),
	CONSTRAINT ck_import_dataset CHECK (dataset IN ('incidents','vehicles','dispatches','trips','fuel','services','crew')),
	FOREIGN KEY(created_by) REFERENCES app_users (user_id)
);
