'use strict';
const financeState={permissions:[],year:null,page:0,identity:null,generation:0};
let financePendingAction=null;
function financeLockNewControls(){
  if(!financePendingAction)return;
  const controls=Array.from($('financeModal')?.querySelectorAll?.('button, input, select, textarea')??[]);
  if($('financeBtn'))controls.push($('financeBtn'));
  for(const control of controls){if(!financePendingAction.controls.has(control))financePendingAction.controls.set(control,control.disabled);control.disabled=true;}
}
function financeControlReady(control,disabled){
  if(!control)return;
  if(financePendingAction){financePendingAction.controls.set(control,disabled);control.disabled=true;}else control.disabled=disabled;
}
function financeReleaseAction(operation){for(const [control,disabled] of operation.controls)control.disabled=disabled;}
function clearFinance(){
  if(financePendingAction){financeReleaseAction(financePendingAction);financePendingAction=null;}
  financeState.generation++;Object.assign(financeState,{identity:null,permissions:[],year:null,page:0});
  for(const id of ['financeContent','financeNav','financeMessage'])if($(id))$(id).innerHTML='';
  if($('financeModal')){$('financeModal').innerHTML='';$('financeModal').remove();}
  if($('financeBtn'))$('financeBtn').classList.add('hidden');
}
async function financeCheckIdentity(ticket,identity){
  let current;try{current=await api('/auth/me')}catch(e){if(e.status===401||e.status===403)clearFinance();throw e}
  if(ticket!==financeState.generation)throw Object.assign(new Error('session state changed'),{cancelled:true});
  if(current.user_id!==identity){clearFinance();throw Object.assign(new Error('session identity changed'),{cancelled:true});}
}
async function financeAPI(url,opt={}){
  const ticket=financeState.generation;
  try{
    const identity=await api('/auth/me');
    if(ticket!==financeState.generation)throw Object.assign(new Error('session state changed'),{cancelled:true});
    if(financeState.identity&&identity.user_id!==financeState.identity){clearFinance();throw Object.assign(new Error('session identity changed'),{cancelled:true});}
    financeState.identity=identity.user_id;
    const result=await api(url,opt);
    await financeCheckIdentity(ticket,identity.user_id);
    if(ticket!==financeState.generation)throw Object.assign(new Error('late finance response discarded'),{cancelled:true});
    return result;
  }catch(e){if(e.status===401||e.status===403)clearFinance();throw e;}
}

const financeKinds={initial:'当初予算',amendment:'補正予算（増減）',transfer:'予算流用',commitment:'支出負担行為',payment:'支出・支払',reversal:'取消・訂正（反対仕訳）'};
const financeCandidateLabels={quote:'見積',request:'予算要求',estimate:'次年度見積'};
const financeEventLabels={delivery:'納品・引渡',inspection:'検査・検収',invoice:'請求書'};
const financeCan=code=>financeState.permissions.includes(code);
const financeJSON=(method,data)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function initFinance(){const p=await financeAPI('/auth/permissions');if(financeState.permissions.some(code=>!p.permissions.includes(code))||(!p.permissions.includes('finance.read')&&!p.permissions.includes('contract.read')))clearFinance();financeState.permissions=p.permissions;$('financeBtn').classList.toggle('hidden',!financeCan('finance.read')&&!financeCan('contract.read'))}
function financeSessionPreflight(target){
 if(target.id!=='financeBtn'&&!target.closest?.('#financeModal'))return ()=>{};
 if(financePendingAction)return ()=>{};
 const operation={controls:new Map(),generation:financeState.generation};financePendingAction=operation;financeLockNewControls();
 return ()=>{if(financePendingAction===operation){financeReleaseAction(operation);financePendingAction=null;}};
}
async function financeAction(fn){
 if(financePendingAction)return;
 const operation={controls:new Map(),generation:financeState.generation};financePendingAction=operation;
 if($('financeMessage'))$('financeMessage').textContent='';financeLockNewControls();
 try{await fn()}catch(e){if(e.cancelled||operation.generation!==financeState.generation||!$('financeMessage'))return;$('financeMessage').textContent=e.status===409?'他の変更または確認後の根拠変更を検出しました。最新情報を読み込み、内容を確認してください。 '+e.message:e.message}
 finally{if(financePendingAction===operation){financeReleaseAction(operation);financePendingAction=null;}}
}
function financeBind(id,fn){if($(id))$(id).onclick=()=>financeAction(fn);financeLockNewControls();}
const financeButtonRequirements={financeEvents:['finance.read','contract.read'],financeAmendments:['finance.read','contract.read'],financeContractEvents:['finance.read','contract.read'],financeContractNew:['finance.read','finance.create','contract.read','contract.create','document.read'],financeContractEdit:['finance.update','contract.read','contract.update'],financeContractApprove:['finance.approve','contract.read','contract.approve','document.read'],financeContractDoc:['contract.read','contract.update','document.read'],financeContractAmend:['finance.read','finance.create','contract.read','contract.update','document.read'],financeContractProfile:['finance.read','finance.update','contract.read','contract.update'],financeContractSupport:['finance.read','contract.read','document.read']};
function financeButton(id,label,perm){return (!perm||financeCan(perm))&&(financeButtonRequirements[id]??[]).every(financeCan)?`<button type="button" class="btn" id="${id}">${esc(label)}</button>`:''}
async function financeAll(path){let rows=[],offset=0;while(true){const p=await financeAPI(path+(path.includes('?')?'&':'?')+new URLSearchParams({limit:'200',offset:String(offset)}));rows.push(...p);if(p.length<200)break;offset+=200}return rows}
async function openFinance(){return financeAction(async()=>{
 await initFinance();if(!$('financeModal')){const wrap=document.createElement('div');wrap.id='financeModal';wrap.className='modalWrap';wrap.style.zIndex='74';wrap.onclick=financeDocumentClick;wrap.innerHTML='<div class="modal" style="width:min(1240px,98vw)"><div class="modalHead"><b>契約・調達・予算</b><span class="grow"></span><button type="button" class="btn" id="financeClose">閉じる</button></div><div class="modalBody"><div id="financeMessage" class="dangerText" role="alert"></div><div id="financeNav" class="toolbar"></div><div id="financeContent"></div></div></div>';document.body.append(wrap);$('financeClose').onclick=()=>wrap.classList.add('hidden')}
 $('financeModal').classList.remove('hidden');$('financeNav').innerHTML=[['financeYears','年度・財務設定','finance.read'],['financeAccounts','予算科目','finance.read'],['financeContracts','契約台帳','contract.read'],['financeParties','契約先','contract.read'],['financeProposals','財務処理・承認','finance.read'],['financeCandidates','見積・要求','finance.read'],['financeEvents','納品・検収・請求','contract.read'],['financeAmendments','契約変更','finance.read'],['financeSummary','執行集計','finance.read'],['financeAlerts','期限・未処理','finance.read'],['financeExchange','CSV・Excel','finance.read']].map(([id,label,perm])=>financeButton(id,label,perm)).join('');
 for(const [id,fn] of Object.entries({financeYears,financeAccounts,financeContracts,financeParties,financeProposals,financeCandidates,financeEvents,financeAmendments,financeSummary,financeAlerts,financeExchange}))financeBind(id,fn);
 await (financeCan('finance.read')?financeProposals:financeContracts)();
});}
function financeTable(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function financeForm(title,fields,values,save,back,explanation=''){
 $('financeContent').innerHTML=`<h2>${esc(title)}</h2>${explanation}<form id="financeForm"><div class="formGrid">${fields.map(f=>{const [key,label,type='text',options=[],required=false]=f;const value=values[key]??'';return `<label>${esc(label)}${type==='select'?`<select id="financeField_${key}" name="${key}" ${required?'required':''}>${options.map(([id,name])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(name)}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="financeField_${key}" name="${key}" ${required?'required':''}>${esc(value)}</textarea>`:`<input id="financeField_${key}" name="${key}" type="${type==='money'?'text':type}" ${type==='money'?'inputmode="decimal"':''} value="${esc(value)}" ${required?'required':''}>`}</label>`}).join('')}</div><p class="notice">金額は正確な十進数で入力してください。保存は草案です。正式反映には根拠確認とHuman承認が必要です。</p><div class="toolbar"><button class="btn primary" id="financeSave">保存</button><button type="button" class="btn" id="financeBack">戻る</button></div></form>`;
 $('financeForm').onsubmit=e=>{e.preventDefault();financeAction(async()=>{const data={};for(const [key,,type] of fields){const value=$('financeField_'+key).value;if(value!=='')data[key]=type==='number'?parseInt(value,10):value}await save(data)})};financeBind('financeBack',back);
}
async function financePicker(key,path,label,selected=null){
 const select=$('financeField_'+key);if(!select)return;
 $('financePick_'+key+'_panel')?.remove();const panel=document.createElement('div');panel.id='financePick_'+key+'_panel';panel.className='toolbar';panel.innerHTML=`<label>${esc(label)}検索<input id="financePick_${key}_q"></label><button type="button" class="btn" id="financePick_${key}_find">検索</button><button type="button" class="btn" id="financePick_${key}_prev">前の候補</button><button type="button" class="btn" id="financePick_${key}_next">次の候補</button><span id="financePick_${key}_page"></span>`;select.closest('label').append(panel);
 let offset=0,q='',generation=0;
 const rowLabel=r=>r.title??r.name??r.original_filename??((financeKinds[r.kind]??financeEventLabels[r.kind]??r.kind)+' / '+r.amount+' '+r.currency+' / '+(r.reason??r.description??''));
 const identities={account_id:'account_id',parent_id:'account_id',to_account_id:'account_id',contract_case_id:'contract_case_id',counterparty_id:'counterparty_id',document_id:'document_id',before_document_id:'document_id',after_document_id:'document_id',commitment_id:'proposal_id',reverses_id:'proposal_id',invoice_id:'event_id',related_event_id:'event_id'};
 const identity=identities[key];if(!identity)throw new Error('Unsupported reference picker');const rowID=r=>{if(!r[identity])throw new Error('Reference record identity missing');return r[identity]};
 async function load(query,start){const run=++generation;const rows=await financeAPI(path+(path.includes('?')?'&':'?')+new URLSearchParams({q:query,limit:'100',offset:String(start)}));if(run!==generation||!document.contains(select))return;offset=start;q=query;const previous=select.value;select.innerHTML='<option value="">選択してください</option>'+rows.map(r=>`<option value="${esc(rowID(r))}">${esc(r.code?r.code+' / '+rowLabel(r):rowLabel(r))}${r.amount!==undefined&&r.title?' / '+esc(r.amount)+' '+esc(r.currency):''}</option>`).join('');
 if(selected&&!rows.some(r=>rowID(r)===selected.id)){select.insertAdjacentHTML('beforeend',`<option value="${esc(selected.id)}">${esc(selected.label)}</option>`)}select.value=previous||(selected?.id??'');financeControlReady($('financePick_'+key+'_prev'),offset===0);financeControlReady($('financePick_'+key+'_next'),rows.length<100);$('financePick_'+key+'_page').textContent=`${start+1}～${start+rows.length}件`;}
 financeBind('financePick_'+key+'_find',()=>load($('financePick_'+key+'_q').value,0));financeBind('financePick_'+key+'_prev',()=>load(q,Math.max(0,offset-100)));financeBind('financePick_'+key+'_next',()=>load(q,offset+100));$('financePick_'+key+'_q').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('financePick_'+key+'_find').click()}};await load('',0);
}
async function financeYearOptions(){return [['','年度を選択'],...(await financeAPI('/finance/years')).map(y=>[y.year_id,y.fiscal_year+' / '+y.currency+' / '+y.status])]}
function financeProof(row){if(!financeCan('document.read'))return '<p>原本参照権限が必要です。</p>';const doc=row.review_snapshot?.document;return row.document_id?`<p>根拠原本: <a target="_blank" rel="noopener noreferrer" href="/documents/${encodeURIComponent(row.document_id)}/download">${esc(doc?.filename??'登録済み原本を開く')}</a>${doc?' / SHA256 '+esc(doc.sha256):''}</p>`:'<p>根拠原本が未登録です。</p>'}
function financeDecision(title,row,fn,back){financeForm(title,[['reason','Human確認・決定理由','textarea',[],true]],{},data=>fn(data.reason),back,`<p>${esc(financeKinds[row.kind]??row.kind??row.title??'年度設定')} / ${esc(row.amount??'')} ${esc(row.currency??'')} / 状態 ${esc(row.status??'')}</p>${financeProof(row)}<details open><summary>確認する根拠・提案値</summary><pre>${esc(JSON.stringify(row,null,2))}</pre></details>`)}
async function financeYears(){const rows=await financeAPI('/finance/years');$('financeContent').innerHTML='<h2>年度・財務設定</h2><p>通貨と許容小数桁は組織で明示しHumanが承認します。自動丸めは行いません。承認済み設定は変更できません。</p>'+financeButton('financeYearNew','年度設定登録','finance.admin')+financeTable(['年度','通貨 / 小数桁','状態','操作'],rows.map(r=>[esc(r.fiscal_year),esc(r.currency)+' / '+esc(r.decimal_places),esc(r.status),r.status==='draft'?`${financeCan('finance.admin')?`<button class="btn" data-finance-year="${r.year_id}">訂正</button>`:''}${financeCan('finance.admin')&&financeCan('finance.approve')?`<button class="btn" data-finance-year-approve="${r.year_id}">Human設定承認</button>`:''}`:'']));financeBind('financeYearNew',()=>financeYearForm());document.querySelectorAll('[data-finance-year]').forEach(b=>b.onclick=()=>financeAction(()=>financeYearForm(rows.find(r=>r.year_id===b.dataset.financeYear))));document.querySelectorAll('[data-finance-year-approve]').forEach(b=>b.onclick=()=>financeAction(()=>{const row=rows.find(r=>r.year_id===b.dataset.financeYearApprove);financeDecision('財務設定Human承認',row,async reason=>{await financeAPI('/finance/years/'+row.year_id+'/approve',financeJSON('POST',{expected_version:row.version,reason}));await financeYears()},financeYears)}))}
function financeYearForm(row=null){const defaults=[['kan','款'],['kou','項'],['moku','目'],['setsu','節'],['saisetsu','細節']];const values={...(row??{currency:'JPY',decimal_places:0}),account_levels:(row?.account_levels??defaults.map(([code,label])=>({code,label}))).map(l=>l.code+':'+l.label).join('\n'),require_invoice_on_payment:String(row?.require_invoice_on_payment??false)};financeForm('年度・本部別財務設定',[...(!row?[['fiscal_year','年度','number',[],true]]:[]),['currency','通貨','select',[['JPY','JPY'],['USD','USD'],['EUR','EUR']],true],['decimal_places','許容小数桁','select',[['0','0桁'],['1','1桁'],['2','2桁']],true],['account_levels','本部別科目階層（上位から1行にコード:表示名）','textarea',[],true],['require_invoice_on_payment','支払の承認済み請求書を必須にする','select',[['false','必須にしない（組織で選択）'],['true','必須にする']],true],['reason','設定根拠','textarea',[],true]],values,async data=>{data.decimal_places=parseInt(data.decimal_places,10);data.require_invoice_on_payment=data.require_invoice_on_payment==='true';data.account_levels=data.account_levels.split('\n').filter(l=>l.trim()).map(line=>{const at=line.indexOf(':');if(at<1)throw new Error('階層をコード:表示名で入力してください');return {code:line.slice(0,at).trim(),label:line.slice(at+1).trim()}});await financeAPI('/finance/years'+(row?'/'+row.year_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,...data}:data));await financeYears()},financeYears)}
async function financeAccounts(){const rows=await financeAll('/finance/accounts');$('financeContent').innerHTML='<h2>予算科目（本部別設定階層）</h2>'+financeButton('financeAccountNew','科目登録','finance.create')+financeTable(['コード','科目','階層','操作'],rows.map(r=>[esc(r.code),esc(r.name),esc(r.level_label??r.level),`<button class="btn" data-finance-account="${r.account_id}">残額・履歴</button>${financeCan('finance.update')?`<button class="btn" data-finance-account-edit="${r.account_id}">名称訂正</button>`:''}`]));financeBind('financeAccountNew',()=>financeAccountForm());document.querySelectorAll('[data-finance-account]').forEach(b=>b.onclick=()=>financeAction(()=>financeAccountDetail(rows.find(r=>r.account_id===b.dataset.financeAccount))));document.querySelectorAll('[data-finance-account-edit]').forEach(b=>b.onclick=()=>financeAction(()=>financeAccountForm(rows.find(r=>r.account_id===b.dataset.financeAccountEdit))))}
async function financeAccountForm(row=null){const years=await financeAPI('/finance/years');const choices=[['','年度を選択'],...years.map(y=>[y.year_id,y.fiscal_year+' / '+y.status])];financeForm(row?'科目名称訂正（コード・年度・階層は固定）':'設定した階層に基づく科目登録',row?[['name','科目名','text',[],true]]:[['year_id','年度','select',choices,true],['level','本部で設定した階層','select',[],true],['parent_id','直上の科目','select',[['','最上位では指定不要']]],['code','科目コード（先頭ゼロを保持）','text',[],true],['name','科目名','text',[],true]],row??{},async data=>{if(data.level)data.level=parseInt(data.level,10);await financeAPI('/finance/accounts'+(row?'/'+row.account_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,...data}:data));await financeAccounts()},financeAccounts);if(!row){async function parents(){const depth=parseInt($('financeField_level').value,10);if(depth===1){$('financeField_parent_id').innerHTML='<option value="">最上位では指定不要</option>';return}await financePicker('parent_id','/finance/accounts?'+new URLSearchParams({year_id:$('financeField_year_id').value,level:String(depth-1)}),'直上科目')};async function policy(){const y=years.find(r=>r.year_id===$('financeField_year_id').value);$('financeField_level').innerHTML=(y?.account_levels??[]).map((l,i)=>`<option value="${i+1}">${esc(l.label)} (${esc(l.code)})</option>`).join('');await parents()};$('financeField_year_id').onchange=()=>financeAction(policy);$('financeField_level').onchange=()=>financeAction(parents);await policy()}}
async function financeAccountDetail(row){const [balance,lines]=await Promise.all([financeAPI('/finance/accounts/'+row.account_id+'/balance'),financeAll('/finance/journal?account_id='+row.account_id)]);$('financeContent').innerHTML=`<h2>${esc(row.code)} / ${esc(row.name)}</h2>`+financeTable(['予算額','予約（負担行為）','執行額','利用可能残額'],[[esc(balance.allocated),esc(balance.reserved),esc(balance.spent),esc(balance.available)]])+financeTable(['日時','予算増減','予約増減','執行増減','根拠'],lines.map(r=>[esc(r.created_at),esc(r.allocated),esc(r.reserved),esc(r.spent),`<button class="btn" data-finance-open="${r.proposal_id}">承認・出典を開く</button>`]));document.querySelectorAll('[data-finance-open]').forEach(b=>b.onclick=()=>financeAction(()=>financeProposalDetail(b.dataset.financeOpen)))}
async function financeParties(){const rows=await financeAll('/finance/counterparties');$('financeContent').innerHTML='<h2>共通契約先台帳</h2>'+financeButton('financePartyNew','契約先登録','contract.create')+financeTable(['名称','登録番号','連絡先','状態','操作'],rows.map(r=>[esc(r.name),esc(r.registration_no??''),esc(r.contact??''),r.active?'有効':'休止',financeCan('contract.update')?`<button class="btn" data-finance-party="${r.counterparty_id}">訂正</button>`:'']));financeBind('financePartyNew',()=>financePartyForm());document.querySelectorAll('[data-finance-party]').forEach(b=>b.onclick=()=>financeAction(()=>financePartyForm(rows.find(r=>r.counterparty_id===b.dataset.financeParty))))}
function financePartyForm(row=null){financeForm('共通契約先', [['name','名称','text',[],true],['registration_no','登録番号'],['address','所在地','textarea'],['contact','連絡先','textarea'],...(row?[['active','状態','select',[['true','有効'],['false','休止']]]]:[])],row??{},async data=>{if(row)data.active=data.active==='true';await financeAPI('/finance/counterparties'+(row?'/'+row.counterparty_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,...data}:data));await financeParties()},financeParties)}
async function financeContracts(q='',offset=0){const rows=await financeAPI('/finance/contracts?'+new URLSearchParams({q,limit:'100',offset:String(offset)}));$('financeContent').innerHTML='<h2>共通契約台帳</h2><div class="toolbar"><input id="financeContractQ" placeholder="名称・番号・契約先検索" value="'+esc(q)+'">'+financeButton('financeContractSearch','検索')+financeButton('financeContractPrev','前へ')+financeButton('financeContractNext','次へ')+financeButton('financeContractNew','契約登録','finance.create')+'</div>'+financeTable(['契約番号 / 件名','契約先','正確な金額','期間','年度 / 状態','操作'],rows.map(r=>[esc(r.contract_no??'')+' / '+esc(r.title),esc(r.counterparty_name??''),esc(r.amount??'未設定')+' '+esc(r.currency),esc(r.start_date??'')+' ～ '+esc(r.end_date??''),esc(r.profile?.year_id?'年度設定済':'年度未設定')+' / '+esc(r.status),`<button class="btn" data-finance-contract="${r.contract_case_id}">契約・根拠</button>`]));financeControlReady($('financeContractPrev'),offset===0);financeControlReady($('financeContractNext'),rows.length<100);financeBind('financeContractSearch',()=>financeContracts($('financeContractQ').value,0));financeBind('financeContractPrev',()=>financeContracts(q,Math.max(0,offset-100)));financeBind('financeContractNext',()=>financeContracts(q,offset+100));financeBind('financeContractNew',()=>financeContractForm());document.querySelectorAll('[data-finance-contract]').forEach(b=>b.onclick=()=>financeAction(()=>financeContractDetail(b.dataset.financeContract)))}
async function financeContractForm(row=null){const years=await financeYearOptions();const fields=[['title','契約件名','text',[],true],...(!row?[['contract_no','契約番号'],['counterparty_id','契約先','select'],['year_id','年度','select',years,true],['document_id','契約根拠原本','select',[],true],['currency','通貨','select',[['JPY','JPY'],['USD','USD'],['EUR','EUR']],true],['renewal_on','設定した更新期限','date']]:[]),['contract_method','契約方法（組織入力）'],['amount','契約額','money',[],true],['start_date','開始日','date'],['end_date','終了日','date']];financeForm(row?'契約草案訂正':'共通契約登録',fields,row??{amount:'0',currency:'JPY'},async data=>{await financeAPI('/finance/contracts'+(row?'/'+row.contract_case_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,...data}:data));await financeContracts()},financeContracts);if(!row){await financePicker('counterparty_id','/finance/counterparties','契約先');await financePicker('document_id','/finance/documents','根拠原本')}}
async function financeContractDetail(id){const r=await financeAPI('/finance/contracts/'+id);$('financeContent').innerHTML=`<h2>${esc(r.title)} / ${esc(r.status)}</h2><p>${esc(r.contract_no??'')} / ${esc(r.counterparty_name??'')} / 契約方法 ${esc(r.contract_method??'')}</p><p>契約額 ${esc(r.amount??'未設定')} ${esc(r.currency)} / ${esc(r.start_date??'')} ～ ${esc(r.end_date??'')} / 更新期限 ${esc(r.profile?.renewal_on??'未設定')}</p><h3>契約原本・根拠</h3>${(r.documents??[]).map(d=>`<p><a target="_blank" rel="noopener noreferrer" href="/documents/${d.document_id}/download">${esc(d.document_role)}原本を開く</a> / SHA256 ${esc(d.sha256)}</p>`).join('')}<div class="toolbar">${r.status==='draft'?financeButton('financeContractEdit','草案訂正','contract.update')+financeButton('financeContractApprove','Human契約承認','contract.approve')+financeButton('financeContractDoc','原本リンク','contract.update'):financeButton('financeContractAmend','根拠付き契約変更草案','finance.create')}${financeButton('financeContractProfile','年度・更新期限設定','finance.update')}${financeButton('financeContractHistory','変更履歴','document.read')}${financeButton('financeContractSupport','根拠・差分・類似案件候補','document.read')}${financeButton('financeContractEvents','納品・検収・請求・支払リンク','finance.read')}</div><div id="financeContractHistoryContent"></div>`;financeBind('financeContractSupport',()=>financeSupport(id));financeBind('financeContractEvents',()=>financeEvents(id));financeBind('financeContractEdit',()=>financeContractForm(r));financeBind('financeContractApprove',()=>financeDecision('契約原本と正確な金額のHuman承認',{...r,document_id:r.documents?.[0]?.document_id},async reason=>{await financeAPI('/finance/contracts/'+id+'/approve',financeJSON('POST',{expected_version:r.version,reason}));await financeContractDetail(id)},()=>financeContractDetail(id)));financeBind('financeContractAmend',()=>financeAmendmentForm(r));financeBind('financeContractDoc',async()=>{financeForm('共通契約原本リンク',[['document_id','原本','select',[],true],['document_role','原本の役割','select',[['contract_source','契約原本'],['specification','仕様書'],['decision','決裁文書'],['delivery','納品原本'],['inspection','検収原本'],['invoice','請求書']],true]],{},async data=>{await financeAPI('/finance/contracts/'+id+'/documents',financeJSON('POST',data));await financeContractDetail(id)},()=>financeContractDetail(id));await financePicker('document_id','/finance/documents','原本')});financeBind('financeContractProfile',async()=>{financeForm('契約の年度・設定した更新期限',[['year_id','年度','select',await financeYearOptions(),true],['renewal_on','更新期限（入力した日付に基づく警告）','date']],r.profile??{},async data=>{await financeAPI('/finance/contracts/'+id+'/profile',financeJSON('PUT',{expected_version:r.profile?.version??r.version,...data}));await financeContractDetail(id)},()=>financeContractDetail(id))});financeBind('financeContractHistory',async()=>{$('financeContractHistoryContent').innerHTML='<pre>'+esc(JSON.stringify(await financeAPI('/finance/contracts/'+id+'/history'),null,2))+'</pre>'})}
async function financeProposals(kind='',status='',offset=0){const rows=await financeAPI('/finance/proposals?'+new URLSearchParams({kind,status,limit:'100',offset:String(offset)}));$('financeContent').innerHTML='<h2>財務処理・Human確認</h2><div class="toolbar"><select id="financeProposalKind"><option value="">全処理</option>'+Object.entries(financeKinds).map(([k,v])=>`<option value="${k}" ${kind===k?'selected':''}>${v}</option>`).join('')+'</select><select id="financeProposalStatus">'+[['','全状態'],['draft','草案'],['reviewed','確認済'],['approved','正式承認'],['cancelled','草案取消']].map(([k,v])=>`<option value="${k}" ${status===k?'selected':''}>${v}</option>`).join('')+'</select>'+financeButton('financeProposalSearch','表示')+financeButton('financeProposalPrev','前へ')+financeButton('financeProposalNext','次へ')+financeButton('financeProposalNew','財務処理草案','finance.create')+'</div>'+financeTable(['処理','正確な金額','理由','状態','操作'],rows.map(r=>[esc(financeKinds[r.kind]),esc(r.amount)+' '+esc(r.currency),esc(r.reason),esc(r.status),`<button class="btn" data-finance-proposal="${r.proposal_id}">根拠・確認</button>`]));financeControlReady($('financeProposalPrev'),offset===0);financeControlReady($('financeProposalNext'),rows.length<100);financeBind('financeProposalSearch',()=>financeProposals($('financeProposalKind').value,$('financeProposalStatus').value));financeBind('financeProposalPrev',()=>financeProposals(kind,status,Math.max(0,offset-100)));financeBind('financeProposalNext',()=>financeProposals(kind,status,offset+100));financeBind('financeProposalNew',()=>financeProposalForm());document.querySelectorAll('[data-finance-proposal]').forEach(b=>b.onclick=()=>financeAction(()=>financeProposalDetail(b.dataset.financeProposal)))}
async function financeProposalForm(kind='initial',row=null,target=null){const keys=Object.entries(financeKinds);const fields=[...(!row&&!target?[['kind','処理','select',keys,true]]:[]),['account_id','予算科目（設定した末端階層）','select',[],true],...(kind==='transfer'?[['to_account_id','流用先の末端科目','select',[],true]]:[]),...(kind==='commitment'||kind==='payment'?[['contract_case_id','共通承認済み契約','select',[],true]]:[]),...(kind==='payment'?[['commitment_id','承認済み支出負担行為','select',[],true],['invoice_id','承認済み請求書（年度設定で必須）','select']]:[]),['amount',kind==='amendment'?'補正額（減額はマイナス）':'金額','money',[],true],['currency','通貨','select',[['JPY','JPY'],['USD','USD'],['EUR','EUR']],true],['document_id','金融処理の根拠原本','select',[],true],['reason','処理の根拠・理由','textarea',[],true]];const key=crypto.randomUUID();financeForm(target?'承認済み処理の取消・訂正草案（履歴を保持）':row?'財務草案訂正':'財務処理草案',fields,row??{kind,amount:target?.amount?.replace(/^-/,'')??'0',currency:target?.currency??'JPY'},async data=>{if(target)data.reverses_id=target.proposal_id;const p=await financeAPI('/finance/proposals'+(row?'/'+row.proposal_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,amount:data.amount,document_id:data.document_id,reason:data.reason}:{kind,idempotency_key:key,...data}));await financeProposalDetail(p.proposal_id)},financeProposals,target?`<p>元処理 ${esc(financeKinds[target.kind])} / ${esc(target.amount)} ${esc(target.currency)}。承認後は反対仕訳を追加し、元の正式履歴を残します。</p>`:'');if($('financeField_kind'))$('financeField_kind').onchange=()=>financeAction(()=>financeProposalForm($('financeField_kind').value));await financePicker('account_id','/finance/accounts?leaf=true','科目',target?{id:target.account_id,label:'元の処理の科目'}:row?{id:row.account_id,label:'草案の科目'}:null);if(kind==='transfer')await financePicker('to_account_id','/finance/accounts?leaf=true','流用先',row?.to_account_id?{id:row.to_account_id,label:'草案に保存した流用先科目'}:null);if(kind==='commitment'||kind==='payment')await financePicker('contract_case_id','/finance/contracts','共通契約',row?.contract_case_id?{id:row.contract_case_id,label:'草案に保存した共通契約'}:null);if(kind==='payment'){await financePicker('commitment_id','/finance/proposals?kind=commitment&status=approved','支出負担行為',row?.commitment_id?{id:row.commitment_id,label:'草案に保存した負担行為'}:null);await financePicker('invoice_id','/finance/procurement-events?kind=invoice&status=approved','請求書',row?.invoice_id?{id:row.invoice_id,label:'草案に保存した請求書'}:null);}await financePicker('document_id','/finance/documents','根拠原本',row?.document_id?{id:row.document_id,label:'草案の登録済み原本'}:null);if(target)financeControlReady($('financeField_account_id'),true);if(row){for(const key of ['account_id','currency','to_account_id','contract_case_id','commitment_id','invoice_id']){if($('financeField_'+key))financeControlReady($('financeField_'+key),true)}}}
async function financeProposalDetail(id){const p=await financeAPI('/finance/proposals/'+id),b=await financeAPI('/finance/accounts/'+p.account_id+'/balance');$('financeContent').innerHTML=`<h2>${esc(financeKinds[p.kind])} / ${esc(p.status)}</h2><p>提案額 <strong>${esc(p.amount)} ${esc(p.currency)}</strong> / ${esc(p.reason)}</p>${financeProof(p)}<p>現在の予算額 ${esc(b.allocated)} / 予約 ${esc(b.reserved)} / 執行 ${esc(b.spent)} / 利用可能残額 <strong id="financeBalance">${esc(b.available)}</strong></p><p>確認者 ${esc(p.reviewed_by??'未確認')} / 承認者 ${esc(p.approved_by??'未承認')}</p><details open><summary>確認時点の科目・契約・原本・金額</summary><pre>${esc(JSON.stringify(p.review_snapshot,null,2))}</pre></details><div class="toolbar">${p.status==='draft'?financeButton('financeProposalEdit','草案訂正','finance.update'):''}${['draft','reviewed'].includes(p.status)?financeButton('financeReview','Human根拠確認','finance.review'):''}${p.status==='reviewed'?financeButton('financeApprove','Human正式承認・仕訳','finance.approve'):''}${['draft','reviewed'].includes(p.status)?financeButton('financeCancel','草案取消','finance.admin'):''}${p.status==='approved'&&p.kind!=='reversal'?financeButton('financeReverse','取消・訂正の反対仕訳草案','finance.create'):''}${p.status==='approved'?financeButton('financeRender','正式原本様式へ差込','finance.export'):''}</div><div id="financeRendered"></div>`;financeBind('financeProposalEdit',()=>financeProposalForm(p.kind,p));for(const [button,action] of [['financeReview','review'],['financeApprove','approve'],['financeCancel','cancel']])financeBind(button,()=>financeDecision(action==='approve'?'Human正式承認（残額に反映）':action==='review'?'Human根拠確認':'草案取消',p,async reason=>{await financeAPI('/finance/proposals/'+id+'/'+action,financeJSON('POST',{expected_version:p.version,reason}));await financeProposalDetail(id)},()=>financeProposalDetail(id)));financeBind('financeReverse',()=>financeProposalForm('reversal',null,p));financeBind('financeRender',async()=>{const templates=await financeAPI('/finance/templates');financeForm('登録済み正式原本へ差込',[['form_template_id','正式原本・版','select',[['','原本を選択'],...templates.map(t=>[t.form_template_id,t.name+' / '+t.version_label])],true]],{},async data=>{const r=await financeAPI('/finance/proposals/'+id+'/render',financeJSON('POST',data));await financeProposalDetail(id);$('financeRendered').innerHTML=`<a class="btn" href="/documents/${r.document_id}/download">正式原本差込結果を取得</a><pre>${esc(JSON.stringify(r.manifest,null,2))}</pre>`},()=>financeProposalDetail(id))})}
async function financeCandidates(){const rows=await financeAll('/finance/candidates');$('financeContent').innerHTML='<h2>根拠付き見積・予算要求・次年度見積</h2><p>組織が取得した見積と根拠だけを登録します。候補は正式残額へ反映されません。</p>'+financeButton('financeCandidateNew','候補登録','finance.create')+financeTable(['種類 / 件名','候補額','状態','根拠・操作'],rows.map(r=>[esc(financeCandidateLabels[r.kind])+' / '+esc(r.title),esc(r.amount)+' '+esc(r.currency),esc(r.status),`<button class="btn" data-finance-candidate="${r.candidate_id}">根拠・Human確認</button>`]));financeBind('financeCandidateNew',()=>financeCandidateForm());document.querySelectorAll('[data-finance-candidate]').forEach(button=>button.onclick=()=>financeAction(()=>{const r=rows.find(x=>x.candidate_id===button.dataset.financeCandidate);$('financeContent').innerHTML=`<h2>${esc(r.title)} / ${esc(r.status)}</h2><p>${esc(financeCandidateLabels[r.kind])} / 候補額 ${esc(r.amount)} ${esc(r.currency)}</p>${financeProof(r)}<pre>${esc(JSON.stringify(r.review_snapshot,null,2))}</pre>${r.status==='candidate'?financeButton('financeCandidateEdit','候補訂正','finance.update')+financeButton('financeCandidateReview','Human候補確認','finance.review')+financeButton('financeCandidateCancel','候補取消','finance.admin'):''}`;financeBind('financeCandidateEdit',()=>financeCandidateForm(r));for(const [id,action] of [['financeCandidateReview','review'],['financeCandidateCancel','cancel']])financeBind(id,()=>financeDecision('候補Human確認（残額へ反映しません）',r,async reason=>{await financeAPI('/finance/candidates/'+r.candidate_id+'/'+action,financeJSON('POST',{expected_version:r.version,reason}));await financeCandidates()},financeCandidates))}))}
async function financeCandidateForm(row=null){financeForm(row?'候補訂正':'証拠に基づく候補登録',[...(!row?[['kind','種類','select',Object.entries(financeCandidateLabels),true],['year_id','要求・見積対象年度','select',await financeYearOptions(),true],['account_id','対象科目','select',[],true]]:[]),['title','件名','text',[],true],['amount','候補額','money',[],true],...(!row?[['currency','通貨','select',[['JPY','JPY'],['USD','USD'],['EUR','EUR']],true]]:[]),['document_id','実際の見積・要求根拠原本','select',[],true],...(!row?[['contract_case_id','関連共通契約（任意）','select'],['counterparty_id','見積提出先（任意）','select']]:[])],row??{amount:'0',currency:'JPY'},async data=>{await financeAPI('/finance/candidates'+(row?'/'+row.candidate_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,title:data.title,amount:data.amount,document_id:data.document_id}:data));await financeCandidates()},financeCandidates);await financePicker('account_id','/finance/accounts?leaf=true','科目');await financePicker('document_id','/finance/documents','原本',row?{id:row.document_id,label:'候補の原本'}:null);if(!row&&financeCan('contract.read')){await financePicker('contract_case_id','/finance/contracts','契約');await financePicker('counterparty_id','/finance/counterparties','見積先')}}
async function financeAmendmentForm(contract){financeForm('承認済み共通契約の変更草案',[['amount','変更後の正式契約額','money',[],true],['end_date','変更後の終了日','date'],['document_id','契約変更の根拠原本','select',[],true],['reason','変更根拠・理由','textarea',[],true]],contract,async data=>{await financeAPI('/finance/contracts/'+contract.contract_case_id+'/amendments',financeJSON('POST',{expected_contract_version:contract.version,...data}));await financeAmendments()},()=>financeContractDetail(contract.contract_case_id),`<p>現在の承認済み契約額 ${esc(contract.amount)} ${esc(contract.currency)} / 終了日 ${esc(contract.end_date??'未設定')}。根拠確認と正式承認後に履歴を追加します。</p>`);await financePicker('document_id','/finance/documents','契約変更原本')}
async function financeAmendments(){const rows=await financeAPI('/finance/amendments');$('financeContent').innerHTML='<h2>共通契約変更・根拠確認</h2>'+financeTable(['変更後金額','終了日','状態','操作'],rows.map(r=>[esc(r.amount),esc(r.end_date??''),esc(r.status),`<button class="btn" data-finance-amendment="${r.amendment_id}">根拠・確認</button>`]));document.querySelectorAll('[data-finance-amendment]').forEach(button=>button.onclick=()=>financeAction(()=>{const r=rows.find(x=>x.amendment_id===button.dataset.financeAmendment);$('financeContent').innerHTML=`<h2>契約変更 / ${esc(r.status)}</h2><p>変更後契約額 ${esc(r.amount)} / 終了日 ${esc(r.end_date??'未設定')} / ${esc(r.reason)}</p>${financeProof(r)}<pre>${esc(JSON.stringify(r.review_snapshot,null,2))}</pre>${['draft','reviewed'].includes(r.status)?financeButton('financeAmendmentReview','Human変更根拠確認','finance.review'):''}${r.status==='reviewed'?financeButton('financeAmendmentApprove','Human契約変更承認','finance.approve'):''}`;for(const [id,action] of [['financeAmendmentReview','review'],['financeAmendmentApprove','approve']])financeBind(id,()=>financeDecision('契約変更のHuman確認・承認',r,async reason=>{await financeAPI('/finance/amendments/'+r.amendment_id+'/'+action,financeJSON('POST',{expected_version:r.version,reason}));await financeAmendments()},financeAmendments))}))}
async function financeSummary(){const options=await financeYearOptions();$('financeContent').innerHTML='<h2>年度別執行・残額集計</h2><select id="financeSummaryYear">'+options.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')+'</select>'+financeButton('financeSummaryLoad','集計')+'<div id="financeSummaryRows"></div>';financeBind('financeSummaryLoad',async()=>{const id=$('financeSummaryYear').value;if(!id)throw new Error('年度を選択してください');const s=await financeAPI('/finance/summary?year_id='+id);$('financeSummaryRows').innerHTML=financeTable(['当初・補正・流用後予算','予約','執行','利用可能残額'],[[esc(s.allocated),esc(s.reserved),esc(s.spent),esc(s.available)]])+financeTable(['科目コード / 名称','予算','予約','執行','利用可能残額','出典'],s.accounts.map(a=>[esc(a.code)+' / '+esc(a.name),esc(a.allocated),esc(a.reserved),esc(a.spent),esc(a.available),`<button class="btn" data-finance-summary-account="${a.account_id}">元仕訳</button>`]));document.querySelectorAll('[data-finance-summary-account]').forEach(b=>b.onclick=()=>financeAction(()=>financeAccountDetail(s.accounts.find(a=>a.account_id===b.dataset.financeSummaryAccount))))})}
async function financeAlerts(){const results=await financeAPI('/finance/alerts');$('financeContent').innerHTML='<h2>更新・期限・Human未処理</h2><p>警告は登録された日付に基づきます。</p>'+financeTable(['契約','期限種別','設定日','操作'],results.contracts.map(r=>[esc(r.title),r.kind==='expiry'?'契約期限':'更新期限',esc(r.due_on)+(r.overdue?' 超過':''),`<button class="btn" data-finance-alert-contract="${r.contract_case_id}">契約</button>`]))+financeTable(['未処理','金額','状態','操作'],results.human_review.map(r=>[esc(financeKinds[r.kind]),esc(r.amount),esc(r.status),`<button class="btn" data-finance-alert-proposal="${r.proposal_id}">確認</button>`]));document.querySelectorAll('[data-finance-alert-contract]').forEach(b=>b.onclick=()=>financeAction(()=>financeContractDetail(b.dataset.financeAlertContract)));document.querySelectorAll('[data-finance-alert-proposal]').forEach(b=>b.onclick=()=>financeAction(()=>financeProposalDetail(b.dataset.financeAlertProposal)))}
async function financeDocumentClick(event){
 const link=event.target.closest('a[href]');const path=link?.getAttribute('href');
 if(path?.startsWith('/documents/')&&path.endsWith('/download')){event.preventDefault();await financeAction(()=>financeDownload(path));}
}
async function financeDownload(path){await financeAPI('/auth/me');const generation=financeState.generation;const response=await fetch(path);if(generation!==financeState.generation)throw Object.assign(new Error('late download discarded'),{cancelled:true});if(!response.ok){if(response.status===401||response.status===403)clearFinance();const result=await response.json();throw new Error(result.detail??'出力できません')}const blob=await response.blob();await financeCheckIdentity(generation,financeState.identity);if(generation!==financeState.generation)throw Object.assign(new Error('late download discarded'),{cancelled:true});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=response.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]??'finance.csv';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
async function financeExchange(){const imports=[['years','年度設定（草案）'],['accounts','科目'],['contracts','共通契約（草案）'],['candidates','見積・要求候補'],['proposals','財務処理（草案）'],['procurement-events','納品・検収・請求（草案）']];const exports=[...imports,['counterparties','共通契約先'],['journal','正式仕訳'],['amendments','契約変更履歴']];$('financeContent').innerHTML=`<h2>CSV・Excel取込 / 出力</h2><p>テンプレートのschema_version=finance-v1を各行に指定し、根拠付きで全行を検証します。UUID参照は出力データを使用できます。正式承認状態は取り込めません。元ファイルを共通原本として保全し、確定前に全行を再検証します。</p><div class="toolbar"><label>取込対象<select id="financeImportDataset">${imports.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>${financeButton('financeImportTemplate','CSVテンプレート','finance.import')}<input id="financeImportFile" type="file" accept=".csv,.xlsx">${financeButton('financeImportPreview','検証プレビュー','finance.import')}</div><div id="financePreviewContent"></div><hr><div class="toolbar"><label>出力対象<select id="financeExportDataset">${exports.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><select id="financeExportFormat"><option value="csv">CSV</option><option value="xlsx">Excel</option></select>${financeButton('financeExportDownload','出力','finance.export')}</div>`;financeBind('financeImportTemplate',()=>financeDownload('/finance/import-template/'+$('financeImportDataset').value));financeBind('financeImportPreview',async()=>{const file=$('financeImportFile').files[0];if(!file)throw new Error('ファイルを選択してください');const data=new FormData();data.append('file',file);const p=await financeAPI('/finance/import/'+$('financeImportDataset').value,{method:'POST',body:data});$('financePreviewContent').innerHTML=`<p>${p.rows}行 / 原本SHA256 ${esc(p.file_sha256)} / 有効期限 ${esc(p.expires_at)}</p><a target="_blank" rel="noopener noreferrer" href="/documents/${p.source_document_id}/download">取込原本</a><pre>${esc(JSON.stringify(p.sample,null,2))}</pre>${financeButton('financeImportConfirm','確認して全行確定','finance.import')}`;financeBind('financeImportConfirm',async()=>{const r=await financeAPI('/finance/import-previews/'+p.preview_id+'/confirm',financeJSON('POST',{expected_version:p.version,file_sha256:p.file_sha256}));$('financePreviewContent').textContent='全行確定 '+r.inserted+'行 / 原本SHA256 '+r.file_sha256})});financeBind('financeExportDownload',()=>financeDownload('/finance/export/'+$('financeExportDataset').value+'?format='+$('financeExportFormat').value))}
async function financeEvents(contractID=''){const rows=await financeAll('/finance/procurement-events'+(contractID?'?contract_case_id='+encodeURIComponent(contractID):''));$('financeContent').innerHTML='<h2>納品・検収・請求・支払リンク</h2><p>原本を確認してHumanが承認します。請求書の承認だけでは予算を執行しません。</p>'+financeButton('financeEventNew','原本に基づく調達段階登録','finance.create')+financeTable(['段階 / 日付','内容','金額','状態','操作'],rows.map(r=>[esc(financeEventLabels[r.kind])+' / '+esc(r.occurred_on),esc(r.description),esc(r.amount)+' '+esc(r.currency),esc(r.status),`<button class="btn" data-finance-event="${r.event_id}">原本・Human確認・支払</button>`]));financeBind('financeEventNew',()=>financeEventForm(null,contractID));document.querySelectorAll('[data-finance-event]').forEach(b=>b.onclick=()=>financeAction(()=>financeEventDetail(b.dataset.financeEvent)))}
async function financeEventForm(row=null,contractID=''){financeForm(row?'調達段階草案訂正':'納品・検収・請求の草案',[...(!row?[['kind','段階','select',Object.entries(financeEventLabels),true],['contract_case_id','共通承認済み契約','select',[],true],['currency','通貨','select',[['JPY','JPY'],['USD','USD'],['EUR','EUR']],true],['related_event_id','先行する承認済み納品・検収（任意）','select']]:[]),['occurred_on','実際の日付','date',[],true],['description','内容・確認事項','textarea',[],true],['amount','原本の金額（該当なしは0）','money',[],true],['document_id','段階の根拠原本','select',[],true]],row??{kind:'delivery',amount:'0',currency:'JPY',occurred_on:new Date().toISOString().slice(0,10)},async data=>{const result=await financeAPI('/finance/procurement-events'+(row?'/'+row.event_id:''),financeJSON(row?'PATCH':'POST',row?{expected_version:row.version,...data}:data));await financeEventDetail(result.event_id)},()=>financeEvents(contractID));await financePicker('document_id','/finance/documents','段階の原本',row?{id:row.document_id,label:'草案の原本'}:null);if(!row){await financePicker('contract_case_id','/finance/contracts','契約',contractID?{id:contractID,label:'現在の共通契約'}:null);await financePicker('related_event_id','/finance/procurement-events?status=approved','先行承認済み段階');$('financeField_kind').onchange=()=>financeAction(async()=>{const kind=$('financeField_kind').value;await financePicker('related_event_id','/finance/procurement-events?status=approved&kind='+(kind==='invoice'?'inspection':'delivery'),'先行段階')})}}
async function financeEventDetail(id){const r=await financeAPI('/finance/procurement-events/'+id);$('financeContent').innerHTML=`<h2>${esc(financeEventLabels[r.kind])} / ${esc(r.status)}</h2><p>${esc(r.occurred_on)} / ${esc(r.description)} / ${esc(r.amount)} ${esc(r.currency)}</p>${financeProof(r)}<details open><summary>Human確認時点の契約・契約先・原本</summary><pre>${esc(JSON.stringify(r.review_snapshot,null,2))}</pre></details><div class="toolbar">${r.status==='draft'?financeButton('financeEventEdit','草案訂正','finance.update'):''}${['draft','reviewed'].includes(r.status)?financeButton('financeEventReview','Human原本確認','finance.review')+financeButton('financeEventCancel','草案取消','finance.admin'):''}${r.status==='reviewed'?financeButton('financeEventApprove','Human段階承認','finance.approve'):''}${financeButton('financeEventContract','共通契約を開く','contract.read')}</div>`+financeTable(['リンクした支払','金額','状態','操作'],(r.payments??[]).map(p=>[esc(p.reason),esc(p.amount)+' '+esc(p.currency),esc(p.status),`<button class="btn" data-finance-event-payment="${p.proposal_id}">支払根拠を開く</button>`]));financeBind('financeEventEdit',()=>financeEventForm(r));financeBind('financeEventContract',()=>financeContractDetail(r.contract_case_id));for(const [button,action] of [['financeEventReview','review'],['financeEventApprove','approve'],['financeEventCancel','cancel']])financeBind(button,()=>financeDecision('調達段階のHuman確認・承認',r,async reason=>{await financeAPI('/finance/procurement-events/'+id+'/'+action,financeJSON('POST',{expected_version:r.version,reason}));await financeEventDetail(id)},()=>financeEventDetail(id)));document.querySelectorAll('[data-finance-event-payment]').forEach(b=>b.onclick=()=>financeAction(()=>financeProposalDetail(b.dataset.financeEventPayment)))}
async function financeSupport(id){const s=await financeAPI('/finance/contracts/'+id+'/support');$('financeContent').innerHTML='<h2>契約の根拠確認支援候補</h2><p>以下は登録済み原本と共通台帳に基づく確認候補です。正式決定はHumanが原本と照合します。</p><p>不足候補: '+esc(s.missing_document_candidates.join(', '))+'</p><h3>登録情報からの文案候補</h3><pre>'+esc(s.draft)+'</pre><h3>同一契約先・契約方法等の類似案件候補</h3>'+financeTable(['件名','金額','操作'],s.similar_cases.map(r=>[esc(r.title),esc(r.amount)+' '+esc(r.currency),`<button class="btn" data-finance-similar="${r.contract_case_id}">共通契約</button>`]))+financeButton('financeSupportExtract','原本文字抽出・OCR候補','document.read')+financeButton('financeSupportDiff','原本差分候補','document.read')+financeButton('financeSupportCalc','金額計算候補','finance.read')+financeButton('financeSupportBack','契約に戻る')+'<div id="financeSupportResult"></div>';financeBind('financeSupportBack',()=>financeContractDetail(id));document.querySelectorAll('[data-finance-similar]').forEach(b=>b.onclick=()=>financeAction(()=>financeContractDetail(b.dataset.financeSimilar)));financeBind('financeSupportExtract',async()=>{financeForm('共通原本の文字抽出・OCR候補',[['document_id','原本','select',[],true]],{},async data=>{const r=await financeAPI('/finance/documents/'+data.document_id+'/extract');$('financeContent').innerHTML='<h2>原本からの抽出候補</h2><pre>'+esc(JSON.stringify(r,null,2))+'</pre>'+financeButton('financeSupportBack','契約支援に戻る');financeBind('financeSupportBack',()=>financeSupport(id))},()=>financeSupport(id));await financePicker('document_id','/finance/documents','原本')});financeBind('financeSupportDiff',async()=>{financeForm('共通原本の差分候補',[['before_document_id','変更前原本','select',[],true],['after_document_id','変更後原本','select',[],true]],{},async data=>{const r=await financeAPI('/finance/document-diff',financeJSON('POST',data));$('financeContent').innerHTML='<h2>原本差分候補</h2><pre>'+esc(JSON.stringify(r,null,2))+'</pre>'+financeButton('financeSupportBack','支援に戻る');financeBind('financeSupportBack',()=>financeSupport(id))},()=>financeSupport(id));await financePicker('before_document_id','/finance/documents','変更前');await financePicker('after_document_id','/finance/documents','変更後')});financeBind('financeSupportCalc',()=>financeForm('十進数の合計候補（正式反映なし）',[['amounts','1行ごとに正確な金額を入力','textarea',[],true]],{},async data=>{const r=await financeAPI('/finance/calculate',financeJSON('POST',{amounts:data.amounts.split('\n').filter(v=>v.trim()).map(v=>v.trim())}));$('financeContent').innerHTML='<h2>金額計算候補</h2><pre>'+esc(JSON.stringify(r,null,2))+'</pre>'+financeButton('financeSupportBack','支援に戻る');financeBind('financeSupportBack',()=>financeSupport(id))},()=>financeSupport(id)))}
