'use strict';
const inquiryState={permissions:[],row:null,sources:[],offset:0,identity:null,generation:0,pending:null,controls:new Set()};
const inquiryCan=p=>inquiryState.permissions.includes('inquiry.'+p);
const inquiryJSON=(method,data)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function clearInquiries(){inquiryState.generation++;Object.assign(inquiryState,{permissions:[],row:null,sources:[],offset:0,identity:null,pending:null,controls:new Set()});if($('inquiryModal')){$('inquiryModal').innerHTML='';$('inquiryModal').remove()}if($('inquiriesBtn'))$('inquiriesBtn').classList.add('hidden')}
async function inquiryAPI(url,opt={}){const ticket=inquiryState.generation;try{const identity=await api('/auth/me');if(ticket!==inquiryState.generation)throw Object.assign(new Error('late inquiry response discarded'),{cancelled:true});if(inquiryState.identity&&identity.user_id!==inquiryState.identity){clearInquiries();throw Object.assign(new Error('session identity changed'),{cancelled:true})}inquiryState.identity=identity.user_id;const r=await api(url,opt);if(ticket!==inquiryState.generation)throw Object.assign(new Error('late inquiry response discarded'),{cancelled:true});return r}catch(e){if(ticket!==inquiryState.generation)throw Object.assign(new Error('late inquiry response discarded'),{cancelled:true});if(e.status===401||e.status===403)clearInquiries();throw e}}

async function initInquiries(){try{const p=await inquiryAPI('/auth/permissions');inquiryState.permissions=p.permissions;$('inquiriesBtn').classList.toggle('hidden',!inquiryCan('read'));return true}catch(e){if(e.cancelled)throw e;if(e.status===401||e.status===403)return false;throw e}}
const inquiryPendingControls=['inquiryAdopt','inquiryEdit','inquiryEvidence','inquiryAI','inquiryReview','inquiryApprove','inquiryRevision','inquiryDelete','inquiryRender','inquiryDraftSave','inquiryHumanSave','inquiryEvidenceSave','inquiryCreate','inquiryImportSave','inquiryRenderSave'];
function inquiryLockControl(control){
  if(typeof control==='string')control=$(control);
  const operation=inquiryState.pending;
  if(!operation||!control)return;
  if(!operation.controls.has(control))operation.controls.set(control,control.disabled);
  control.disabled=true;
}
async function inquiryAction(fn){
  if(inquiryState.pending)return;
  const operation={generation:inquiryState.generation,controls:new Map()};
  inquiryState.pending=operation;
  for(const control of inquiryState.controls){
    if(control.isConnected===false)inquiryState.controls.delete(control);
    else inquiryLockControl(control);
  }
  inquiryPendingControls.forEach(inquiryLockControl);
  if($('inquiryMessage'))$('inquiryMessage').textContent='';
  try{await fn()}
  catch(e){
    if(e.cancelled||operation.generation!==inquiryState.generation)return;
    if($('inquiryMessage'))$('inquiryMessage').textContent=e.status===409?'変更・根拠の更新を検出しました。最新の内容を確認してください。 '+e.message:e.message;
  }
  finally{
    if(inquiryState.pending===operation&&operation.generation===inquiryState.generation){
      inquiryState.pending=null;
      for(const [control,disabled] of operation.controls)control.disabled=disabled;
    }
  }
}
function inquiryRegisterControl(control){if(control){inquiryState.controls.add(control);inquiryLockControl(control)}}
function inquiryBindControl(control,fn,event='onclick'){if(control){control[event]=()=>inquiryAction(fn);inquiryRegisterControl(control)}}
function inquiryBind(id,fn){inquiryBindControl($(id),fn)}
function inquiryControlReady(id,disabled){const control=$(id);if(!control)return;if(inquiryState.pending?.controls.has(control)){inquiryState.pending.controls.set(control,disabled);control.disabled=true}else control.disabled=disabled}
function inquiryButton(id,label,p){return !p||inquiryCan(p)?`<button type="button" class="btn" id="${id}">${esc(label)}</button>`:''}
async function openInquiries(){if(!await initInquiries())return;if(!$('inquiryModal')){const w=document.createElement('div');w.id='inquiryModal';w.className='modalWrap';w.style.zIndex='77';w.innerHTML='<div class="modal" style="width:min(1240px,98vw)"><div class="modalHead"><b>議会・照会 / 根拠付き回答</b><span class="grow"></span><button class="btn" id="inquiryClose">閉じる</button></div><div class="modalBody"><div id="inquiryMessage" class="dangerText" role="alert"></div><div class="toolbar"><button class="btn" id="inquiryList">過去の質問・年度検索</button><button class="btn" id="inquiryExchange">CSV・Excel</button></div><div id="inquiryContent"></div></div></div>';document.body.append(w);$('inquiryClose').onclick=()=>{const canRead=inquiryCan('read');clearInquiries();$('inquiriesBtn').classList.toggle('hidden',!canRead)}}$('inquiryModal').classList.remove('hidden');inquiryBind('inquiryList',inquiryList);inquiryBind('inquiryExchange',inquiryExchange);await inquiryAction(inquiryList)}
async function inquiryList(){ $('inquiryContent').innerHTML='<h2>過去の質問と回答</h2><div class="toolbar"><label>年度<input id="inquiryYear" type="number" min="1900" max="2200" placeholder="全年度"></label><label>質問・回答<input id="inquiryQuery"></label><button class="btn" id="inquiryFind">検索</button><button class="btn" id="inquirySimilar">語句の類似検索</button>'+inquiryButton('inquiryNew','質問登録','create')+'</div><p>類似検索は語句一致による候補です。意味の一致・正確性を保証しません。</p><div id="inquiryResults"></div><div class="toolbar"><button class="btn" id="inquiryPrev">前の100件</button><button class="btn" id="inquiryNext">次の100件</button></div>';inquiryBind('inquiryNew',inquiryNew);inquiryState.offset=0;inquiryBind('inquiryFind',()=>{inquiryState.offset=0;return inquiryResults(false)});inquiryBind('inquirySimilar',()=>{inquiryState.offset=0;return inquiryResults(true)});inquiryBind('inquiryPrev',()=>{inquiryState.offset=Math.max(0,inquiryState.offset-100);return inquiryResults(false)});inquiryBind('inquiryNext',()=>{inquiryState.offset+=100;return inquiryResults(false)});await inquiryResults(false)}
async function inquiryResults(similar){const q=$('inquiryQuery').value,year=$('inquiryYear').value;let params=new URLSearchParams({q,limit:'100',...(!similar?{offset:String(inquiryState.offset)}:{})});if(year)params.set('year',year);if(similar&&!q)throw new Error('類似検索の語句を入力してください');const data=await inquiryAPI('/inquiries'+(similar?'/similar':'')+'?'+params);const rows=similar?data.items:data;inquiryControlReady('inquiryPrev',similar||inquiryState.offset===0);inquiryControlReady('inquiryNext',similar||rows.length<100);$('inquiryResults').innerHTML='<table><thead><tr><th>年度</th><th>質問</th><th>状態</th><th>回答・根拠</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.year)}</td><td>${esc(r.question)}</td><td>${esc(r.status)}${similar?' / '+esc(r.score):''}</td><td><button class="btn" data-inquiry="${r.inquiry_id}">開く</button></td></tr>`).join('')+'</tbody></table>';document.querySelectorAll('[data-inquiry]').forEach(b=>inquiryBindControl(b,()=>inquiryDetail(b.dataset.inquiry)))}
async function inquiryNew(){ $('inquiryContent').innerHTML='<h2>質問登録</h2><form id="inquiryNewForm"><label>年度<input id="inquiryNewYear" type="number" min="1900" max="2200" required value="'+new Date().getFullYear()+'"></label><label>質問<textarea id="inquiryQuestion" required maxlength="20000"></textarea></label><button class="btn" id="inquiryCreate">登録</button></form>';inquiryRegisterControl($('inquiryCreate'));$('inquiryNewForm').onsubmit=e=>{e.preventDefault();inquiryAction(async()=>{const r=await inquiryAPI('/inquiries',inquiryJSON('POST',{year:Number($('inquiryNewYear').value),question:$('inquiryQuestion').value}));await inquiryDetail(r.inquiry_id)})}}
function inquiryProof(r){return '<h3>選択した根拠と引用</h3>'+r.evidence.map(e=>`<div class="card"><b>${esc(e.source_type)} / ${esc(e.source_id)}</b><pre>${esc(e.excerpt)}</pre><p>取得日 ${esc(e.retrieved_at)} / 原記録Version ${esc(e.snapshot.record_version??'SHAで検証')} / 原記録日 ${esc(e.snapshot.source_date)}</p><pre>${esc(JSON.stringify(e.snapshot.values,null,2))}</pre><button class="btn" data-inquiry-source="${e.evidence_id}">原記録・原本を開く</button>${e.snapshot.documents.map(d=>`<a target="_blank" rel="noopener noreferrer" href="/documents/${d.document_id}/download">原本 ${esc(d.sha256)}</a>`).join(' ')}${r.status!=='approved'&&inquiryCan('update')?` <button class="btn" data-inquiry-remove="${e.evidence_id}">根拠を削除</button>`:''}</div>`).join('')}
async function inquiryDetail(id){const r=await inquiryAPI('/inquiries/'+id);inquiryState.row=r;$('inquiryContent').innerHTML=`<h2>${esc(r.year)}年度 / ${esc(r.question)}</h2><p>状態: <b>${esc(r.status)}</b> / Version ${r.version}${r.revision_of?' / 承認済み親回答: '+esc(r.revision_of):''}</p><h3>${r.status==='approved'?'Human承認済み回答':'回答草案（正式回答とは別）'}</h3><pre>${esc(r.draft)}</pre><h3>数値の根拠</h3><pre>${esc(JSON.stringify(r.claims,null,2))}</pre>${inquiryProof(r)}<div class="toolbar">${r.status!=='approved'?inquiryButton('inquiryEvidence','根拠を選択・引用','update')+inquiryButton('inquiryEdit','回答草案を編集','update')+inquiryButton('inquiryAI','AI Draft候補','create')+inquiryButton('inquiryReview','Human根拠確認','review')+inquiryButton('inquiryDelete','質問草案を削除','admin'):inquiryButton('inquiryRevision','新しい回答改訂','create')+inquiryButton('inquiryRender','原様式へ出力','export')}${r.status==='reviewed'?inquiryButton('inquiryApprove','Human正式承認','approve'):''}</div><p>確認者 ${esc(r.reviewed_by??'未確認')} / ${esc(r.reviewed_at??'')}　承認者 ${esc(r.approved_by??'未承認')} / ${esc(r.approved_at??'')}</p><details><summary>作成・モデル・入力の来歴</summary><pre>${esc(JSON.stringify(r.provenance,null,2))}</pre></details><div id="inquiryCandidateContent"></div>`;inquiryBind('inquiryEvidence',()=>inquiryEvidence(r));inquiryBind('inquiryEdit',()=>inquiryEdit(r));for(const [button,action] of [['inquiryReview','review'],['inquiryApprove','approve'],['inquiryRevision','revisions'],['inquiryDelete','delete']])inquiryBind(button,()=>inquiryDecision(r,action));inquiryBind('inquiryAI',async()=>{const c=await inquiryAPI('/inquiries/'+id+'/ai-draft',inquiryJSON('POST',{expected_version:r.version,reason:'職員が根拠付き候補作成を依頼'}));await inquiryCandidate(r,c)});inquiryBind('inquiryRender',()=>inquiryRender(r));document.querySelectorAll('[data-inquiry-source]').forEach(b=>inquiryBindControl(b,()=>inquirySource(r.evidence.find(e=>e.evidence_id===b.dataset.inquirySource))));document.querySelectorAll('[data-inquiry-remove]').forEach(b=>inquiryBindControl(b,async()=>{await inquiryAPI('/inquiries/'+id+'/evidence/'+b.dataset.inquiryRemove,inquiryJSON('DELETE',{expected_version:r.version,reason:'職員が根拠の削除を確認'}));await inquiryDetail(id)}));const candidates=await inquiryAPI('/inquiries/'+id+'/candidates');if(candidates.length)await inquiryCandidate(r,candidates[0])}
async function inquirySource(e){const s=await inquiryAPI('/inquiries/source/'+e.source_type+'/'+e.source_id);if(s.navigation.href){window.open(s.navigation.href,'_blank','noopener');return}const w=document.createElement('div');w.className='card';w.id='inquirySourcePreview';w.innerHTML='<h3>権限を再検証した原記録</h3><pre>'+esc(s.text)+'</pre><p>原記録Version '+esc(s.record_version??'SHA検証')+' / '+esc(s.source_date)+'</p>';const old=$('inquirySourcePreview');if(old)old.remove();$('inquiryContent').append(w);w.scrollIntoView({block:'nearest'});const navigation={personnel:()=>window.open('/ui/admin.html','_blank','noopener'),emergency:()=>openUnifiedSearchHit('emergency','emergency_case',e.source_id,'',''),facility:()=>openUnifiedSearchHit('facilities','facility',e.source_id,e.source_id,''),contract:()=>openUnifiedSearchHit('contracts','contract_case',e.source_id,'',''),finance:()=>openUnifiedSearchHit('budget','finance_proposals',e.source_id,'',''),incident:()=>openUnifiedSearchHit('operations','incident',e.source_id,'',''),vehicle:()=>openUnifiedSearchHit('fleet','vehicle',e.source_id,'',''),asset:()=>openUnifiedSearchHit('operational_assets','operational_asset',e.source_id,'',''),workforce:()=>workforceAction(openWorkforce),fire:()=>openUnifiedSearchHit('fire','fire_investigation_case',e.source_id,'','')};if(navigation[e.source_type]){const b=document.createElement('button');b.className='btn';b.textContent='共通モジュールで開く';inquiryBindControl(b,navigation[e.source_type]);w.append(b)}}
async function inquiryEvidence(r){const labels={document:['原本','document.read'],personnel:['職員台帳','personnel.read'],emergency:['救急事案','emergency.case.read'],facility:['対象物','facility.read'],contract:['共通契約','contract.read'],finance:['財務処理','finance.read'],incident:['事案','incident.read'],vehicle:['車両','fleet.read'],asset:['資機材','asset.read'],workforce:['勤務','workforce.read'],legal:['法令','legal_source.read'],fire:['火災調査','fire_investigation.read']};$('inquiryContent').innerHTML='<h2>権限内の原記録・共通原本を選択</h2><div class="toolbar"><label>根拠の種類<select id="inquirySourceType">'+Object.entries(labels).filter(([,v])=>inquiryState.permissions.includes(v[1])).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')+'</select></label><input id="inquirySourceQuery" placeholder="原記録の語句"><button class="btn" id="inquirySourceFind">根拠を検索</button></div><select id="inquirySourceSelect"></select><div id="inquirySourceText"></div><form id="inquiryEvidenceForm"><label>取得した原文からの引用<textarea id="inquiryExcerpt" required maxlength="10000"></textarea></label><button class="btn" id="inquiryEvidenceSave">根拠と引用を保存</button></form>';const display=()=>{const s=inquiryState.sources[Number($('inquirySourceSelect').value)];$('inquirySourceText').innerHTML=s?'<pre>'+esc(s.text)+'</pre><p>原記録Version '+esc(s.record_version??'SHA検証')+'</p>':'';$('inquiryExcerpt').value=s?s.text.slice(0,10000):''};const find=async()=>{inquiryState.sources=await inquiryAPI('/inquiries/sources?'+new URLSearchParams({source_type:$('inquirySourceType').value,q:$('inquirySourceQuery').value}));$('inquirySourceSelect').innerHTML=inquiryState.sources.map((s,i)=>`<option value="${i}">${esc(s.text.slice(0,160))}</option>`).join('');display()};inquiryBind('inquirySourceFind',find);inquiryBindControl($('inquirySourceType'),find,'onchange');$('inquirySourceSelect').onchange=display;inquiryRegisterControl($('inquiryEvidenceSave'));$('inquiryEvidenceForm').onsubmit=e=>{e.preventDefault();inquiryAction(async()=>{const s=inquiryState.sources[Number($('inquirySourceSelect').value)];if(!s)throw new Error('根拠を選択してください');await inquiryAPI('/inquiries/'+r.inquiry_id+'/evidence',inquiryJSON('POST',{expected_version:r.version,source_type:s.source_type,source_id:s.source_id,query_parameters:{query:$('inquirySourceQuery').value},excerpt:$('inquiryExcerpt').value}));await inquiryDetail(r.inquiry_id)})};await find()}
async function inquiryEdit(r){let claims=JSON.parse(JSON.stringify(r.claims));$('inquiryContent').innerHTML='<h2>回答草案の編集</h2><p>回答中の各数値に、原記録の正確な値・単位を選択してください。未根拠の数値は保存・確認できません。編集後はHuman確認をやり直します。</p><form id="inquiryDraftForm"><label>年度<input id="inquiryEditYear" type="number" min="1900" max="2200" required></label><label>質問<textarea id="inquiryEditQuestion" required></textarea></label><label>回答草案<textarea id="inquiryDraft" maxlength="50000" rows="8"></textarea></label><div id="inquiryClaims"></div><button type="button" class="btn" id="inquiryClaimAdd">数値の根拠を追加</button><button class="btn" id="inquiryDraftSave">草案を保存</button></form>';$('inquiryEditYear').value=r.year;$('inquiryDraft').value=r.draft;$('inquiryEditQuestion').value=r.question;
 const render=()=>{$('inquiryClaims').innerHTML=claims.map((c,i)=>`<div class="card" data-claim-row="${i}"><label>根拠<select data-claim-evidence="${i}">${r.evidence.map(e=>`<option value="${e.evidence_id}" ${e.evidence_id===c.evidence_id?'selected':''}>${esc(e.excerpt.slice(0,100))}</option>`).join('')}</select></label><label>原記録の数値<select data-claim-value="${i}"></select></label><label>回答中の数値表記<input data-claim-text="${i}" value="${esc(c.text)}"></label><span data-claim-unit="${i}"></span><button type="button" class="btn" data-claim-remove="${i}">数値根拠を削除</button>${c.formula&&c.formula!=='identity'?'<p>宣言済み計算式 '+esc(c.formula)+' / 根拠付き計算結果（変更時は削除して再登録）</p>':''}</div>`).join('');claims.forEach((c,i)=>{const evidence=document.querySelector(`[data-claim-evidence="${i}"]`),values=document.querySelector(`[data-claim-value="${i}"]`),text=document.querySelector(`[data-claim-text="${i}"]`),unit=document.querySelector(`[data-claim-unit="${i}"]`);const update=()=>{const e=r.evidence.find(e=>e.evidence_id===evidence.value);if(!e)return;values.innerHTML=e.snapshot.values.map((v,j)=>`<option value="${j}">${esc(v.value)} ${esc(v.unit)}</option>`).join('');let n=e.snapshot.values.findIndex(v=>v.value===c.value&&v.unit===c.unit);values.value=String(n<0?0:n);unit.textContent=c.unit??'';if(c.formula&&c.formula!=='identity'){values.disabled=true;evidence.disabled=true;text.readOnly=true}};update();values.onchange=()=>{const e=r.evidence.find(e=>e.evidence_id===evidence.value),v=e?.snapshot.values[Number(values.value)];if(v){Object.assign(c,v,{evidence_id:e.evidence_id,formula:'identity',operands:[]});text.value=c.text;unit.textContent=c.unit}};evidence.onchange=()=>{c.evidence_id=evidence.value;c.value='';update();values.onchange()};text.oninput=()=>c.text=text.value;document.querySelector(`[data-claim-remove="${i}"]`).onclick=()=>{claims.splice(i,1);render()}})};render();$('inquiryClaimAdd').onclick=()=>{const e=r.evidence.find(e=>e.snapshot.values.length);if(!e){$('inquiryMessage').textContent='数値を含む根拠を先に選択してください';return}claims.push({...e.snapshot.values[0],evidence_id:e.evidence_id,formula:'identity',operands:[]});render()};inquiryRegisterControl($('inquiryDraftSave'));$('inquiryDraftForm').onsubmit=e=>{e.preventDefault();inquiryAction(async()=>{await inquiryAPI('/inquiries/'+r.inquiry_id,inquiryJSON('PATCH',{expected_version:r.version,year:Number($('inquiryEditYear').value),question:$('inquiryEditQuestion').value,draft:$('inquiryDraft').value,claims}));await inquiryDetail(r.inquiry_id)})}}
async function inquiryDecision(r,action){$('inquiryContent').innerHTML='<h2>'+esc(action==='approve'?'Human正式承認':action==='review'?'Human根拠確認':action==='revisions'?'承認済み回答から改訂を作成':'草案削除')+'</h2><pre>'+esc(r.draft)+'</pre>'+inquiryProof(r)+'<form id="inquiryDecisionForm"><label><input type="checkbox" id="inquiryHumanChecked" required> 原記録・引用・数値と回答の整合を確認しました</label><label>確認・承認理由<textarea id="inquiryReason" required maxlength="4000"></textarea></label><button class="btn" id="inquiryHumanSave">明示的に確定</button></form>';inquiryRegisterControl($('inquiryHumanSave'));$('inquiryDecisionForm').onsubmit=e=>{e.preventDefault();inquiryAction(async()=>{if(!$('inquiryHumanChecked').checked)throw new Error('根拠を確認してください');const row=await inquiryAPI('/inquiries/'+r.inquiry_id+(action==='delete'?'':'/'+action),inquiryJSON(action==='delete'?'DELETE':'POST',{expected_version:r.version,reason:$('inquiryReason').value}));if(action==='delete')await inquiryList();else await inquiryDetail(row.inquiry_id)})};document.querySelectorAll('[data-inquiry-source]').forEach(b=>inquiryBindControl(b,()=>inquirySource(r.evidence.find(e=>e.evidence_id===b.dataset.inquirySource))))}
async function inquiryCandidate(r,c){$('inquiryCandidateContent').innerHTML='<h3>AI Draft候補（草案・正式回答への自動反映なし）</h3><pre>'+esc(c.draft)+'</pre><p>モデル '+esc(c.model)+' / '+esc(c.model_version)+' / Confidence '+esc(c.confidence??'未評価')+' / '+esc(c.generated_at)+'</p><details><summary>入力・根拠の来歴</summary><pre>'+esc(JSON.stringify(c.input_provenance,null,2))+'</pre></details>'+inquiryButton('inquiryAdopt','根拠を検証して草案に採用','update');inquiryBind('inquiryAdopt',async()=>{await inquiryAPI('/inquiries/'+r.inquiry_id+'/adopt-candidate',inquiryJSON('POST',{expected_version:r.version,candidate_id:c.candidate_id,reason:'職員が候補と根拠を確認して草案に採用'}));await inquiryDetail(r.inquiry_id)})}
async function inquiryRender(r){const ts=await inquiryAPI('/inquiries/templates');$('inquiryContent').innerHTML='<h2>支給された原様式への正式回答出力</h2><p>登録済み原様式の指定欄へ記入します。原様式未登録の場合は管理者が原本と欄の対応を登録してください。</p><select id="inquiryTemplate">'+ts.map(t=>`<option value="${t.form_template_id}">${esc(t.name)} / ${esc(t.version_label)}</option>`).join('')+'</select>'+inquiryButton('inquiryRenderSave','原様式へ出力','export')+'<div id="inquiryRendered"></div>';inquiryBind('inquiryRenderSave',async()=>{if(!$('inquiryTemplate').value)throw new Error('原様式を選択してください');const x=await inquiryAPI('/inquiries/'+r.inquiry_id+'/render',inquiryJSON('POST',{form_template_id:$('inquiryTemplate').value}));$('inquiryRendered').innerHTML=`<a href="/documents/${x.document_id}/download" target="_blank" rel="noopener noreferrer">原様式による回答を取得</a><pre>${esc(JSON.stringify(x.manifest,null,2))}</pre>`})}
async function inquiryDownload(path){await inquiryAPI('/auth/permissions');const ticket=inquiryState.generation,r=await fetch(path);if(ticket!==inquiryState.generation)return;if(!r.ok){const d=await r.json();if(r.status===401||r.status===403)clearInquiries();throw new Error(d.detail??'出力できません')}const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=r.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]??'inquiries.csv';a.click();URL.revokeObjectURL(u)}
async function inquiryExchange(){$('inquiryContent').innerHTML='<h2>CSV・Excel取込 / 出力</h2><p>inquiries-v1: year, question, draft, claims, evidence, history。全行・全原記録を検証し、草案としてまとめて登録します。正式確認・承認は取り込みません。原本SHAと行番号を保持します。</p><div class="toolbar"><select id="inquiryFormat"><option value="csv">CSV</option><option value="xlsx">Excel</option></select>'+inquiryButton('inquiryExport','権限内の回答・根拠を出力','export')+inquiryButton('inquiryImportTemplate','空の取込様式','import')+'</div><input type="file" id="inquiryImportFile" accept=".csv,.xlsx">'+inquiryButton('inquiryImportSave','全行を検証して取込','import')+'<div id="inquiryImportResult"></div>';inquiryBind('inquiryExport',()=>inquiryDownload('/inquiries/export?format='+$('inquiryFormat').value));inquiryBind('inquiryImportTemplate',()=>inquiryDownload('/inquiries/import-template?format='+$('inquiryFormat').value));inquiryBind('inquiryImportSave',async()=>{const f=$('inquiryImportFile').files[0];if(!f)throw new Error('ファイルを選択してください');const d=new FormData();d.append('file',f);const r=await inquiryAPI('/inquiries/import',{method:'POST',body:d});$('inquiryImportResult').innerHTML='<p>全行確定 '+r.inserted+'行 / SHA256 '+esc(r.file_sha256)+'</p><a href="/documents/'+r.source_document_id+'/download" target="_blank" rel="noopener noreferrer">取込原本</a>'})}
