'use strict';
const state={permissions:new Set(),task:'ocr',corrections:[],sets:[],artifacts:[],evaluations:[],history:[],champion:{version:1},cases:[],selected:new Set(),sourceOffset:0,correctionOffset:0};
let requestGeneration=0;
class StaleRequest extends Error {}
const labels={ocr:'OCR補正',proper_names:'地名・固有名詞',audio_correction:'音声認識補正',document_correction:'文書修正',document_classification:'書類分類',facility_linking:'対象物紐付け',photo_classification:'写真分類',workflow_pattern:'業務確認パターン'};
const el=id=>document.getElementById(id);const message=text=>{el('message').textContent=text;};
function clearSensitive(){
 requestGeneration++;state.permissions=new Set();state.task='ocr';state.corrections=[];state.sets=[];state.artifacts=[];state.evaluations=[];state.history=[];state.champion={version:1};state.cases=[];state.selected.clear();state.sourceOffset=0;state.correctionOffset=0;
 for(const id of ['loginForm','sourceSearch','correctionForm','caseForm','setForm','suggestForm'])el(id).reset();
 el('humanReason').value='';
 for(const id of ['setEvidence','suggestion','champion'])el(id).textContent='';
 for(const id of ['task','corrections','evaluationSets','evaluations','history','cases','correctionSource','evaluationSources','artifactSelect','setSelect'])el(id).replaceChildren();
 el('workspace').hidden=true;el('loginSection').hidden=false;
}
function report(error){if(!(error instanceof StaleRequest))message(error.message);}
async function request(path,method='GET',body){const generation=requestGeneration;const response=await fetch(path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(generation!==requestGeneration)throw new StaleRequest();if(!response.ok){if(response.status===401)clearSensitive();throw new Error(response.status===409?'内容または版が変わりました。再読込して証拠を確認してください。':typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));}return result;}
function reason(){const value=el('humanReason').value.trim();if(!value)throw new Error('確認・実行理由を入力してください。');return value;}
function td(row,value){const cell=document.createElement('td');cell.textContent=String(value??'');row.appendChild(cell);return cell;}
function button(cell,label,callback,permission){const item=document.createElement('button');item.textContent=label;item.disabled=permission&&!state.permissions.has(permission);item.addEventListener('click',()=>perform(callback));cell.appendChild(item);}
function select(id,records,key,name){const node=el(id),previous=node.value;node.replaceChildren();for(const row of records)node.appendChild(new Option(name(row),row[key]));if([...node.options].some(item=>item.value===previous))node.value=previous;}
async function perform(callback){try{const result=await callback();if(result===false)return;message('保存・確認しました。');await refreshTask();}catch(error){report(error);}}
async function confirmAction(path,body,description){body.reason=reason();if(!window.confirm(description+'\n理由: '+body.reason))return false;return request(path,'POST',body);}
async function sourceSearch(offset=0){const task=state.task;state.sourceOffset=offset;const q=new FormData(el('sourceSearch')).get('q');const sources=await request('/learning/sources?'+new URLSearchParams({task,q,offset:String(offset)}));if(state.task!==task)return;for(const id of ['correctionSource','evaluationSources'])select(id,sources,'document_id',row=>row.name+' ['+row.sha256.slice(0,12)+']');el('sourceNext').disabled=sources.length<100;}
function render(){
 el('champion').textContent='現在のChampion版: '+state.champion.version+' / '+(state.champion.artifact_id?'確認済み修正辞書':'補正なしのBaseline');
 el('corrections').replaceChildren();for(const item of state.corrections){const row=document.createElement('tr'),choice=td(row,'');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=state.selected.has(item.correction_id);checkbox.disabled=item.review_status!=='approved'||!state.permissions.has('learning.evaluate');checkbox.addEventListener('change',()=>checkbox.checked?state.selected.add(item.correction_id):state.selected.delete(item.correction_id));choice.appendChild(checkbox);td(row,item.input_text);td(row,item.output_text);const source=td(row,(item.synthetic?'合成例':item.source_sha256.slice(0,12))+' / '+item.review_status);if(item.source_document_id){const link=document.createElement('a');link.textContent=' 原本を開く';link.href='/documents/'+encodeURIComponent(item.source_document_id)+'/download';source.appendChild(link);}const action=td(row,'');if(item.review_status==='pending')for(const [decision,label] of [['approved','確認済みにする'],['rejected','却下']])button(action,label,()=>confirmAction('/learning/corrections/'+item.correction_id+'/review',{expected_version:item.version,decision},'原本と修正後の内容を確認しましたか？'),'learning.review');el('corrections').appendChild(row);}
 el('evaluationSets').replaceChildren();for(const item of state.sets){const row=document.createElement('tr');const name=td(row,item.name);button(name,'入力・正解を見る',()=>{el('setEvidence').textContent=JSON.stringify({name:item.name,cases:item.cases,originals:item.source_evidence,sha256:item.cases_sha256},null,2);});td(row,item.cases.length+'件 / '+(item.synthetic?'合成評価':item.source_evidence.length+'原本'));td(row,item.review_status);const action=td(row,'');if(item.review_status==='pending')for(const [decision,label] of [['approved','正解を確認済みにする'],['rejected','却下']])button(action,label,()=>confirmAction('/learning/evaluation-sets/'+item.evaluation_set_id+'/review',{expected_version:item.version,decision},'固定評価の全入力・Human正解・原本を確認しましたか？'),'learning.review');el('evaluationSets').appendChild(row);}
 select('artifactSelect',state.artifacts,'artifact_id',row=>row.artifact_sha256.slice(0,12)+' / '+row.training_evidence.length+'修正');select('setSelect',state.sets.filter(row=>row.review_status==='approved'),'evaluation_set_id',row=>row.name+' / '+row.cases_sha256.slice(0,12));
 el('evaluations').replaceChildren();for(const item of state.evaluations){const row=document.createElement('tr');const candidate=state.artifacts.find(record=>record.artifact_id===item.artifact_id),fixed=state.sets.find(record=>record.evaluation_set_id===item.evaluation_set_id);td(row,(candidate?.artifact_sha256.slice(0,12)||item.artifact_id)+' / '+(fixed?.name||item.evaluation_set_id));td(row,(item.result.champion.exact_accuracy*100).toFixed(1)+'%');td(row,(item.result.candidate.exact_accuracy*100).toFixed(1)+'%');const acceptable=item.result.no_regression&&item.result.strict_improvement;td(row,acceptable?'改善あり・ケース別退行なし':'昇格条件未達');const action=td(row,'');if(acceptable&&item.champion_version===state.champion.version)button(action,'Human承認して昇格',()=>confirmAction('/learning/champions/'+state.task+'/promote',{evaluation_id:item.evaluation_id,expected_version:state.champion.version},'比較証拠を確認し、この候補をChampionへ昇格しますか？'),'learning.promote');el('evaluations').appendChild(row);}
 el('history').replaceChildren();for(const item of state.history){const row=document.createElement('tr');td(row,item.applied_version);td(row,item.action+' / '+item.reason);td(row,item.selected_artifact_id?'修正辞書':'補正なし');const action=td(row,'');if(item.applied_version===state.champion.version)button(action,'直前のChampionへ戻す',()=>confirmAction('/learning/champions/'+state.task+'/rollback',{transition_id:item.transition_id,expected_version:state.champion.version},'現在の変更を取り消して直前のChampionへ戻しますか？'),'learning.promote');el('history').appendChild(row);}
}
function renderCases(){el('cases').replaceChildren();state.cases.forEach((item,index)=>{const row=document.createElement('tr');td(row,item.input);td(row,item.expected);button(td(row,''),'除く',()=>{state.cases.splice(index,1);renderCases();});el('cases').appendChild(row);});}
async function refreshTask(){const task=state.task,query='?task='+encodeURIComponent(task);const results=await Promise.all([request('/learning/corrections'+query+'&limit=100'),request('/learning/evaluation-sets'+query),request('/learning/artifacts'+query),request('/learning/evaluations'+query),request('/learning/champions/'+task+'/history'),request('/learning/champions/'+task)]);if(state.task!==task)return;[state.corrections,state.sets,state.artifacts,state.evaluations,state.history,state.champion]=results;state.correctionOffset=state.corrections.length;el('correctionOlder').disabled=state.corrections.length<100;render();}
async function start(){clearSensitive();try{const context=await request('/learning/context');state.permissions=new Set(context.permissions);select('task',context.tasks.map(task=>({task})),'task',row=>labels[row.task]);state.task=el('task').value;if(!state.task)throw new Error('学習対象の原本参照権限がありません。');el('loginSection').hidden=true;el('workspace').hidden=false;for(const node of document.querySelectorAll('[data-permission]'))node.hidden=!state.permissions.has(node.dataset.permission);for(const id of ['syntheticCorrectionLabel','syntheticSetLabel'])el(id).hidden=context.production_mode||!state.permissions.has('account.manage');await Promise.all([sourceSearch(),refreshTask()]);message(context.username+' / 提案と正式データは分離しています。');}catch(error){report(error);}}
el('loginForm').addEventListener('submit',async event=>{event.preventDefault();try{const data=new FormData(event.target);await request('/auth/login','POST',Object.fromEntries(data));event.target.reset();await start();}catch(error){report(error);}});
el('sourceSearch').addEventListener('submit',event=>{event.preventDefault();sourceSearch().catch(report);});el('sourceNext').addEventListener('click',()=>sourceSearch(state.sourceOffset+100).catch(report));
el('task').addEventListener('change',()=>{requestGeneration++;state.task=el('task').value;state.cases=[];el('setEvidence').textContent='';el('suggestion').textContent='';state.selected.clear();renderCases();Promise.all([sourceSearch(),refreshTask()]).catch(report);});
el('refreshButton').addEventListener('click',()=>refreshTask().catch(report));
el('correctionForm').addEventListener('submit',event=>{event.preventDefault();perform(async()=>{const form=new FormData(event.target),synthetic=form.get('synthetic')==='on';await request('/learning/corrections','POST',{task:state.task,input_text:form.get('input_text'),output_text:form.get('output_text'),source_document_id:synthetic?null:form.get('source_document_id')||null,synthetic,reason:reason()});event.target.reset();});});
el('correctionOlder').addEventListener('click',async()=>{try{const task=state.task;const rows=await request('/learning/corrections?'+new URLSearchParams({task,limit:'100',offset:String(state.correctionOffset)}));if(state.task!==task)return;state.corrections.push(...rows);state.correctionOffset+=rows.length;el('correctionOlder').disabled=rows.length<100;render();}catch(error){report(error);}});
el('buildButton').addEventListener('click',()=>perform(()=>confirmAction('/learning/artifacts',{task:state.task,correction_ids:[...state.selected]},'選択した確認済み修正から辞書Candidateを作成しますか？')));
el('caseForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);if(state.cases.length>=100){message('評価セットは100ケースまでです。');return;}state.cases.push({input:data.get('input'),expected:data.get('expected')});event.target.reset();renderCases();});
el('setForm').addEventListener('submit',event=>{event.preventDefault();perform(async()=>{const data=new FormData(event.target);const saved=await confirmAction('/learning/evaluation-sets',{task:state.task,name:data.get('name'),synthetic:data.get('synthetic')==='on',source_document_ids:[...el('evaluationSources').selectedOptions].map(option=>option.value),cases:state.cases},'固定入力・Human正解・評価用原本を保存しますか？');if(saved===false)return false;state.cases=[];renderCases();event.target.reset();});});
el('evaluateButton').addEventListener('click',()=>perform(()=>request('/learning/artifacts/'+el('artifactSelect').value+'/evaluate','POST',{evaluation_set_id:el('setSelect').value})));
el('suggestForm').addEventListener('submit',async event=>{event.preventDefault();try{const data=new FormData(event.target),result=await request('/learning/suggest','POST',{task:state.task,input_text:data.get('input_text')});el('suggestion').textContent='元の出力:\n'+result.original+'\n\n提案（Human確認待ち）:\n'+result.suggestion+'\n\nChampion版: '+result.champion_version;}catch(error){report(error);}});
el('logoutButton').addEventListener('click',async()=>{clearSensitive();try{await request('/auth/logout','POST');message('ログアウトしました。');}catch(error){report(error);}});
start();
