// Shared /ui/ shell: session cookie, escaping, API helper and modal styling.
const operationsState={permissions:[],incident:null,vehicle:null,dispatch:null,listType:'incidents',offset:0,q:''};
function clearOperations(){Object.assign(operationsState,{permissions:[],incident:null,vehicle:null,dispatch:null,listType:'incidents',offset:0,q:''});if($('operationsModal'))$('operationsModal').remove();$('operationsBtn')?.classList.add('hidden')}
const operationsCan=p=>operationsState.permissions.includes(p);
const operationsJSON=(method,data)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function operationsAction(fn){$('operationsMessage').textContent='';try{await fn()}catch(e){if(e.cancelled||!$('operationsMessage'))return;$('operationsMessage').textContent=e.status===409?'更新競合または根拠変更があります。「再読込」で最新記録を開いてください。':(Array.isArray(e.body?.detail)?e.body.detail.map(d=>d.loc.join('.')+': '+d.msg).join(' / '):String(e.message))}}
async function initOperations(isCurrent=()=>true){try{if(!isCurrent())return;const r=await api('/auth/permissions');if(!isCurrent())return;operationsState.permissions=r.permissions;$('operationsBtn').classList.toggle('hidden',!r.permissions.some(p=>p.startsWith('incident.')||p.startsWith('fleet.')))}catch(e){if(e.cancelled)throw e;}}
function operationsButton(id,label,permission){return !permission||operationsCan(permission)?`<button class="btn" id="${id}" type="button">${esc(label)}</button>`:''}
function operationsBind(id,fn){if($(id))$(id).onclick=()=>operationsAction(fn)}
const operationKinds=[['fire','火災'],['rescue','救助'],['emergency_support','救急支援'],['watch','警戒'],['storm','風水害'],['other','その他']];
function operationsOptions(rows,key,label,blank=true){return [...(blank?[['','未指定']]:[]),...rows.map(r=>[r[key],label(r)])]}
function operationsField([key,label,type='text',options=[]],values={}){
  let value=values[key]??'';
  if(type==='datetime-local'&&value){const d=new Date(/(Z|[+-]\d\d:\d\d)$/.test(value)?value:value+'Z');if(!Number.isNaN(d.valueOf()))value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
  const attrs=`id="operationsField_${key}" name="${key}"`;
  const input=type==='select'?`<select ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:type==='textarea'?`<textarea ${attrs}>${esc(value)}</textarea>`:`<input ${attrs} type="${type}" ${type==='number'?`step="${key.includes('odometer')?'0.1':'0.01'}" min="0"`:''} value="${esc(value)}">`;
  return `<label class="field">${esc(label)}${input}</label>`;
}
function operationsValues(fields,patch=false){const values={};for(const [key,,type] of fields){let value=$(`operationsField_${key}`).value;if(value===''){if(patch)values[key]=null;continue}if(type==='datetime-local')value=new Date(value).toISOString();if(key==='active')value=value==='true';values[key]=value}return values}
function operationsForm(title,fields,values,save,back){
  $('operationsContent').innerHTML=`<h2>${esc(title)}</h2><form id="operationsForm"><div class="grid2">${fields.map(f=>operationsField(f,values)).join('')}</div><div class="toolbar"><button class="btn primary" type="submit">保存</button><button class="btn" id="operationsFormBack" type="button">戻る</button></div></form>`;
  $('operationsForm').onsubmit=e=>{e.preventDefault();operationsAction(()=>save(operationsValues(fields,Boolean(values.version))))};operationsBind('operationsFormBack',back);
}
async function openOperations(isCurrent=()=>true){
  if(!isCurrent())return;await initOperations(isCurrent);if(!isCurrent())return;
  if(!$('operationsModal')){
    const el=document.createElement('div');el.id='operationsModal';el.className='modalWrap';el.style.zIndex='72';
    el.innerHTML='<div class="modal" style="width:min(1220px,98vw)"><div class="modalHead"><b>事案・出動 / 車両運用</b><span class="grow"></span><button class="btn" id="operationsClose">閉じる</button></div><div class="modalBody"><div id="operationsMessage" class="dangerText" role="alert"></div><div id="operationsNav" class="toolbar"></div><div id="operationsContent"></div></div></div>';
    document.body.append(el);$('operationsClose').onclick=()=>el.classList.add('hidden');
  }
  $('operationsModal').classList.remove('hidden');
  $('operationsNav').innerHTML=operationsButton('operationsIncidents','事案','incident.read')+operationsButton('operationsVehicles','車両','fleet.read')+operationsButton('operationsSummary','月次・年次集計',null)+operationsButton('operationsAlerts','期限・故障警告','fleet.read')+operationsButton('operationsRates','手当設定','incident.read')+operationsButton('operationsExchange','取込・出力');
  operationsBind('operationsIncidents',()=>operationsList('incidents',0,''));operationsBind('operationsVehicles',()=>operationsList('vehicles',0,''));operationsBind('operationsSummary',operationsSummary);operationsBind('operationsAlerts',operationsAlerts);operationsBind('operationsRates',operationsRates);operationsBind('operationsExchange',operationsExchange);
  const modal=$('operationsModal'),owned=()=>isCurrent()&&$('operationsModal')===modal&&modal.isConnected&&!modal.classList.contains('hidden');
  await operationsAction(()=>operationsCan('incident.read')?operationsList('incidents',0,'',owned):operationsCan('fleet.read')?operationsList('vehicles',0,'',owned):operationsSummary());
}
async function operationsList(type=operationsState.listType,offset=0,q=operationsState.q,isCurrent=()=>true){try{
  if(!isCurrent())return;Object.assign(operationsState,{listType:type,offset,q});const domain=type==='incidents'?'incident':'fleet';
  const rows=await api('/operations/'+type+'?'+new URLSearchParams({q,offset:String(offset),limit:'50'}));if(!isCurrent())return;
  $('operationsContent').innerHTML=`<div class="toolbar"><label>検索<input id="operationsQ" value="${esc(q)}"></label><button class="btn" id="operationsSearch">検索</button>${operationsButton('operationsNew','新規登録',domain+'.create')}</div><table><thead><tr><th>番号 / コード</th><th>名称</th><th>状態</th><th>住所 / 距離</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.number??r.source?.number??r.code??'')}</td><td>${esc(r.title??r.name)}</td><td>${esc(r.status??(r.active?'使用中':'休止'))}</td><td>${esc(r.address??r.source?.address??r.odometer??'')}</td><td><button class="btn" data-operations-open="${esc(r.incident_id??r.vehicle_id)}">開く</button></td></tr>`).join('')}</tbody></table><div class="toolbar"><button class="btn" id="operationsPrev">前へ</button><button class="btn" id="operationsNext">次へ</button></div>`;
  operationsBind('operationsSearch',()=>operationsList(type,0,$('operationsQ').value));$('operationsQ').onkeydown=e=>{if(e.key==='Enter')$('operationsSearch').click()};operationsBind('operationsNew',()=>type==='incidents'?operationsIncidentForm():operationsVehicleForm());
  document.querySelectorAll('[data-operations-open]').forEach(b=>b.onclick=()=>operationsAction(()=>type==='incidents'?operationsIncidentDetail(b.dataset.operationsOpen):operationsVehicleDetail(b.dataset.operationsOpen)));
  $('operationsPrev').disabled=offset===0;$('operationsNext').disabled=rows.length<50;operationsBind('operationsPrev',()=>operationsList(type,Math.max(0,offset-50),q));operationsBind('operationsNext',()=>operationsList(type,offset+50,q));
}catch(error){if(isCurrent())throw error;}}
async function operationsIncidentForm(row=null){
  const linked=Boolean(row&&(row.emergency_case_id||row.fire_investigation_case_id||row.source_restricted));
  const fields=[['kind','種別','select',operationKinds],['title','事案名'],...(!linked?[['occurred_at','覚知日時','datetime-local'],['address','住所'],['number','番号']]:[]),['notes','記録','textarea']];
  operationsForm(row?'事案訂正':'事案登録',fields,row??{},async values=>{
    if(row)await api('/operations/incidents/'+row.incident_id,operationsJSON('PATCH',{expected_version:row.version,...values}));
    else{const source=$('operationsSourceType').value;const id=$('operationsSourceID').value;if(source&&id){delete values.address;delete values.number;delete values.occurred_at;values[source]=id;values.kind=source==='emergency_case_id'?'emergency_support':'fire'}else if(source)throw new Error('元事案を選択してください');row=await api('/operations/incidents',operationsJSON('POST',values))}
    await operationsIncidentDetail(row.incident_id);
  },()=>row?operationsIncidentDetail(row.incident_id):operationsList('incidents'));
  if(!row){
    const panel=document.createElement('div');panel.innerHTML=`<p class="notice">元の救急・火災調査事案とリンクする場合、住所・日時・番号は元記録を参照します。</p><label class="field">元事案<select id="operationsSourceType"><option value="">リンクなし</option>${operationsCan('emergency.case.read')?'<option value="emergency_case_id">救急事案</option>':''}${operationsCan('fire_investigation.read')?'<option value="fire_investigation_case_id">火災調査</option>':''}</select></label><div class="toolbar"><label>元事案検索<input id="operationsSourceQuery"></label><button class="btn" type="button" id="operationsFindSource">候補検索</button></div><label class="field">選択<select id="operationsSourceID"><option value="">未選択</option></select></label>`;
    $('operationsForm').prepend(panel);operationsBind('operationsFindSource',operationsFindSource);$('operationsSourceType').onchange=()=>operationsAction(async()=>{const linked=Boolean($('operationsSourceType').value);for(const key of ['address','number','occurred_at'])$(`operationsField_${key}`).disabled=linked;await operationsFindSource()});
  }
}
async function operationsFindSource(){
  const type=$('operationsSourceType').value;if(!type){$('operationsSourceID').innerHTML='<option value="">未選択</option>';return}
  const rows=await api((type==='emergency_case_id'?'/emergency/cases':'/fire-investigations')+'?'+new URLSearchParams({q:$('operationsSourceQuery').value,limit:'200'}));
  $('operationsSourceID').innerHTML='<option value="">未選択</option>'+rows.map(r=>`<option value="${esc(r[type])}">${esc(r.dispatch_number??r.case_number??'番号未設定')} / ${esc(r.call_date??r.title??'')} / ${esc(r.incident_address??r.location_text??'')}</option>`).join('');
}
async function operationsIncidentDetail(id,isCurrent=()=>true){try{
  if(!isCurrent())return;const row=await api('/operations/incidents/'+id);if(!isCurrent())return;
  const dispatches=row.source_restricted?[]:await api('/operations/incidents/'+id+'/dispatches');if(!isCurrent())return;operationsState.incident=row;
  $('operationsContent').innerHTML=`<h2>${esc(row.title)}</h2><p>${esc(row.kind)} / ${esc(row.status)} / ${esc(row.source?.number??row.number??'')} / ${esc(row.source?.address??row.address??'')}</p><p>${esc(row.notes)}</p>${row.source?`<p class="notice">元事案ID ${esc(row.source.source_id)} v${row.source.version} / ${esc(row.source.occurred_at??row.source.call_date??'')} ${esc(row.source.call_time??'')}</p>`:''}${row.source_restricted?'<p class="notice">元記録の参照権限が必要です。</p>':''}<div class="toolbar">${operationsButton('operationsReload','再読込')}${row.status==='active'&&!row.source_restricted?operationsButton('operationsEdit','事案訂正','incident.update')+operationsButton('operationsDispatchNew','出動登録','incident.create')+operationsButton('operationsCancel','事案取消','incident.admin'):''}</div><h3>出動隊</h3><table><thead><tr><th>隊</th><th>出場</th><th>帰署</th><th>状態</th><th>正式手当</th><th></th></tr></thead><tbody>${dispatches.map(d=>`<tr><td>${esc(d.unit)}</td><td>${esc(d.departed_at)}</td><td>${esc(d.returned_at)}</td><td>${esc(d.status)}</td><td>${esc(d.official_amount??'')}</td><td><button class="btn" data-operations-dispatch="${esc(d.dispatch_id)}">開く</button></td></tr>`).join('')}</tbody></table>`;
  operationsBind('operationsReload',()=>operationsIncidentDetail(id));operationsBind('operationsEdit',()=>operationsIncidentForm(row));operationsBind('operationsDispatchNew',()=>operationsDispatchForm());operationsBind('operationsCancel',()=>operationsHumanAction('/incidents/'+id+'/cancel',row,()=>operationsIncidentDetail(id),'事案を取消'));
  document.querySelectorAll('[data-operations-dispatch]').forEach(b=>b.onclick=()=>operationsAction(()=>operationsDispatchDetail(b.dataset.operationsDispatch)));
}catch(error){if(isCurrent())throw error;}}
async function operationsVehicleForm(row=null){
  const fields=[...(!row?[['code','車両コード'],['odometer','初期距離 km','number']]:[]),['name','名称'],['registration','登録番号'],...(row?[['active','運用状態','select',[['true','使用中'],['false','休止']]]]:[]),['notes','記録','textarea']];
  operationsForm(row?'車両訂正':'車両登録',fields,row??{odometer:0},async values=>{const r=await api(row?'/operations/vehicles/'+row.vehicle_id:'/operations/vehicles',operationsJSON(row?'PATCH':'POST',row?{expected_version:row.version,...values}:values));await operationsVehicleDetail(r.vehicle_id)},()=>row?operationsVehicleDetail(row.vehicle_id):operationsList('vehicles'));
}
async function operationsDispatchForm(row=null){
  const vehicles=operationsCan('fleet.read')?await api('/operations/vehicles?limit=200'):[];
  const fields=[['unit','出動隊'],['vehicle_id','車両','select',operationsOptions(vehicles,'vehicle_id',v=>v.code+' / '+v.name)],['departed_at','出場','datetime-local'],['arrived_at','現着','datetime-local'],['returned_at','帰署','datetime-local'],['activity','活動','textarea'],['report','報告','textarea'],...(operationsCan('document.read')?[['document_id','共通原本ID（任意）']]:[])];
  operationsForm(row?'出動訂正':'出動登録',fields,row??{},async values=>{const r=await api(row?'/operations/dispatches/'+row.dispatch_id:'/operations/incidents/'+operationsState.incident.incident_id+'/dispatches',operationsJSON(row?'PATCH':'POST',{expected_version:row?.version??operationsState.incident.version,...values}));await operationsDispatchDetail(r.dispatch_id)},()=>row?operationsDispatchDetail(row.dispatch_id):operationsIncidentDetail(operationsState.incident.incident_id));
}
async function operationsDispatchDetail(id,isCurrent=()=>true){try{
  if(!isCurrent())return;const d=await api('/operations/dispatches/'+id);if(!isCurrent())return;
  const crew=operationsCan('incident.crew.read')?await api('/operations/dispatches/'+id+'/crew'):[];if(!isCurrent())return;operationsState.dispatch=d;
  const editable=d.status==='draft';
  $('operationsContent').innerHTML=`<h2>${esc(d.unit)} / ${esc(d.status)}</h2><p>出場 ${esc(d.departed_at)} / 現着 ${esc(d.arrived_at)} / 帰署 ${esc(d.returned_at)}</p><p>車両ID ${esc(d.vehicle_id??'未指定')}</p><p>${esc(d.activity)}</p><p>${esc(d.report)}</p><p>手当候補 ${esc(d.candidate_amount??'未計算')} / 正式手当 ${esc(d.official_amount??'未承認')}</p>${d.calculation?`<details><summary>計算根拠</summary><pre>${esc(JSON.stringify(d.calculation,null,2))}</pre></details>`:''}<p>確認者 ${esc(d.reviewed_by??'')} / 承認者 ${esc(d.approved_by??'')} / ${esc(d.review_note??'')}</p><p>取消 ${esc(d.cancellation_note??'')}</p><div class="toolbar">${operationsButton('operationsReload','再読込')}${operationsButton('operationsParent','事案へ')}${editable?operationsButton('operationsEdit','出動訂正','incident.update')+operationsButton('operationsCrewNew','隊員登録','incident.crew.manage')+operationsButton('operationsCalculate','承認済み単価で候補計算','incident.update')+operationsButton('operationsReview','Human確認','incident.review'):''}${d.status==='reviewed'?operationsButton('operationsApprove','Human正式承認','incident.approve'):''}${d.status!=='cancelled'?operationsButton('operationsCancel','出動取消','incident.admin'):''}</div><h3>隊員</h3><table><thead><tr><th>共通職員ID</th><th>役割</th><th></th></tr></thead><tbody>${crew.map(c=>`<tr><td>${esc(c.employee_id)}</td><td>${esc(c.role)}</td><td>${editable&&operationsCan('incident.crew.manage')?`<button class="btn" data-operations-crew-remove="${esc(c.crew_id)}">解除</button>`:''}</td></tr>`).join('')}</tbody></table>`;
  operationsBind('operationsReload',()=>operationsDispatchDetail(id));operationsBind('operationsParent',()=>operationsIncidentDetail(d.incident_id));operationsBind('operationsEdit',()=>operationsDispatchForm(d));operationsBind('operationsCrewNew',()=>operationsCrewForm(d));operationsBind('operationsCalculate',()=>operationsCalculate(d));
  for(const [button,action,label] of [['operationsReview','/review','出動報告・手当候補を確認'],['operationsApprove','/approve','出動報告・手当を正式承認'],['operationsCancel','/cancel','出動を取消']])operationsBind(button,()=>operationsHumanAction('/dispatches/'+id+action,d,()=>operationsDispatchDetail(id),label));
  document.querySelectorAll('[data-operations-crew-remove]').forEach(b=>b.onclick=()=>operationsAction(()=>operationsHumanAction('/crew/'+b.dataset.operationsCrewRemove+'/remove',d,()=>operationsDispatchDetail(id),'隊員割当を解除')));
}catch(error){if(isCurrent())throw error;}}
async function operationsCrewForm(d){
  const employees=await api('/operations/employees');const fields=[['employee_id','共通職員','select',operationsOptions(employees,'employee_id',e=>(e.employee_code??'')+' / '+e.display_name)],['role','役割']];
  operationsForm('隊員割当',fields,{},async values=>{await api('/operations/dispatches/'+d.dispatch_id+'/crew',operationsJSON('POST',{expected_version:d.version,...values}));await operationsDispatchDetail(d.dispatch_id)},()=>operationsDispatchDetail(d.dispatch_id));
}
async function operationsCalculate(d){
  const rates=(await api('/operations/allowance-rates')).filter(r=>r.status==='approved');const fields=[['rate_id','承認済み単価','select',operationsOptions(rates,'rate_id',r=>r.label+' / '+r.amount+' / '+r.basis+' / '+r.rounding)]];
  operationsForm('手当候補計算（正式決定はHuman承認）',fields,{},async values=>{await api('/operations/dispatches/'+d.dispatch_id+'/calculate',operationsJSON('POST',{expected_version:d.version,...values}));await operationsDispatchDetail(d.dispatch_id)},()=>operationsDispatchDetail(d.dispatch_id));
}
async function operationsHumanAction(path,row,back,label,extra={}){
  operationsForm(label,[['note','確認・決定理由','textarea']],{},async values=>{if(!values.note)throw new Error('確認・決定理由を入力してください');await api('/operations'+path,operationsJSON('POST',{expected_version:row.version,...extra,...values}));await back()},back);
}
async function operationsRates(){
  const rates=await api('/operations/allowance-rates');$('operationsContent').innerHTML='<p class="notice">組織で承認された単価と根拠を登録してください。既定の法定・財務単価はありません。単価はHuman承認後に候補計算へ使用できます。承認済み単価は変更できません。</p>'+operationsButton('operationsRateNew','単価草案登録','incident.admin')+`<table><thead><tr><th>コード / 単価</th><th>計算単位</th><th>根拠</th><th>状態</th><th></th></tr></thead><tbody>${rates.map(r=>`<tr><td>${esc(r.code)} / ${esc(r.label)} / ${esc(r.amount)}</td><td>${esc(r.basis)} / ${esc(r.rounding)}</td><td>${esc(r.approval_reference)}</td><td>${esc(r.status)}</td><td>${r.status==='draft'&&operationsCan('incident.approve')?`<button class="btn" data-operations-rate="${esc(r.rate_id)}">Human承認</button>`:''}</td></tr>`).join('')}</tbody></table>`;
  operationsBind('operationsRateNew',()=>{const fields=[['code','単価コード'],['label','名称'],['amount','金額','number'],['basis','計算単位','select',[['per_dispatch','1出動'],['per_crew','隊員数'],['per_hour','出場から帰署の時間']]],['rounding','組織が承認した端数処理','select',[['','選択してください'],['half_up','小数2桁に四捨五入'],['half_even','小数2桁に偶数丸め'],['down','小数2桁で切捨て']]],['approval_reference','組織が承認した根拠','textarea']];operationsForm('単価草案',fields,{},async values=>{await api('/operations/allowance-rates',operationsJSON('POST',values));await operationsRates()},operationsRates)});
  document.querySelectorAll('[data-operations-rate]').forEach(b=>b.onclick=()=>operationsAction(()=>operationsHumanAction('/allowance-rates/'+b.dataset.operationsRate+'/approve',rates.find(r=>r.rate_id===b.dataset.operationsRate),operationsRates,'単価をHuman承認')));
}
async function operationsVehicleDetail(id,isCurrent=()=>true){try{
  if(!isCurrent())return;const v=await api('/operations/vehicles/'+id);if(!isCurrent())return;
  const h=await api('/operations/vehicles/'+id+'/history');if(!isCurrent())return;operationsState.vehicle=v;
  $('operationsContent').innerHTML=`<h2>${esc(v.code)} / ${esc(v.name)}</h2><p>${v.active?'使用中':'休止'} / 距離 ${esc(v.odometer)} km / 車両割当燃料在庫 ${esc(v.fuel_stock)} L</p><p>次回車検・点検 ${esc(v.next_inspection_on??'未設定')} / 次回整備 ${esc(v.next_service_on??'未設定')} / 次回整備距離 ${esc(v.next_service_odometer??'未設定')}</p><p>${esc(v.notes)}</p><div class="toolbar">${operationsButton('operationsReload','再読込')}${operationsButton('operationsEdit','車両訂正','fleet.update')}${v.active?operationsButton('operationsTripNew','運行登録','fleet.create')+operationsButton('operationsFuelNew','燃料登録','fleet.create')+operationsButton('operationsServiceNew','点検・車検・修理・故障','fleet.create'):''}</div><h3>運行履歴</h3>${operationsHistoryTable(h.trips,['started_at','ended_at','start_odometer','end_odometer','purpose','dispatch_id','driver_employee_id'])}<h3>燃料履歴</h3>${operationsHistoryTable(h.fuel,['occurred_at','kind','liters','amount','notes'])}<h3>点検・整備履歴</h3><table><thead><tr><th>日付</th><th>種別 / 内容</th><th>費用</th><th>状態</th><th>期限候補</th><th></th></tr></thead><tbody>${h.services.map(s=>`<tr><td>${esc(s.performed_on)}</td><td>${esc(s.kind)} / ${esc(s.description)}${s.resolved_by_service_id?' / 解消済み':''}</td><td>${esc(s.cost)}</td><td>${esc(s.status)}</td><td>${esc(s.next_inspection_on??'')} / ${esc(s.next_service_on??'')} / ${esc(s.next_service_odometer??'')}</td><td>${s.status==='draft'&&operationsCan('fleet.review')?`<button class="btn" data-operations-service="${s.service_id}" data-action="review">Human確認</button>`:''}${s.status==='reviewed'&&operationsCan('fleet.approve')?`<button class="btn" data-operations-service="${s.service_id}" data-action="approve">Human承認・期限反映</button>`:''}${['draft','reviewed'].includes(s.status)&&operationsCan('fleet.admin')?`<button class="btn" data-operations-service="${s.service_id}" data-action="cancel">取消</button>`:''}</td></tr>`).join('')}</tbody></table><p class="notice">運行・燃料は追記履歴です。承認済み整備は編集できません。未承認の期限は車両へ反映されません。</p>`;
  operationsBind('operationsReload',()=>operationsVehicleDetail(id));operationsBind('operationsEdit',()=>operationsVehicleForm(v));operationsBind('operationsTripNew',()=>operationsTripForm(v));operationsBind('operationsFuelNew',()=>operationsFuelForm(v));operationsBind('operationsServiceNew',()=>operationsServiceForm(v));
  document.querySelectorAll('[data-operations-service]').forEach(b=>b.onclick=()=>operationsAction(()=>operationsHumanAction('/services/'+b.dataset.operationsService+'/'+b.dataset.action,h.services.find(s=>s.service_id===b.dataset.operationsService),()=>operationsVehicleDetail(id),b.dataset.action==='approve'?'点検・整備と期限を正式承認':'点検・整備の確認 / 取消',b.dataset.action==='approve'?{expected_vehicle_version:v.version,...(h.services.find(s=>s.service_id===b.dataset.operationsService).resolves_fault_id?{expected_fault_version:h.services.find(s=>s.service_id===h.services.find(r=>r.service_id===b.dataset.operationsService).resolves_fault_id)?.version}:{})}:{})));
}catch(error){if(isCurrent())throw error;}}
function operationsHistoryTable(rows,keys){return `<div style="overflow:auto"><table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function operationsTripForm(v){
  let dispatches=[];
  if(operationsCan('incident.read')){const incidents=await api('/operations/incidents?limit=200');for(const i of incidents.filter(i=>!i.source_restricted&&i.status==='active')){const ds=await api('/operations/incidents/'+i.incident_id+'/dispatches');dispatches.push(...ds.filter(d=>d.vehicle_id===v.vehicle_id&&d.status!=='cancelled').map(d=>({...d,label:i.title+' / '+d.unit})))}}
  const employees=operationsCan('incident.crew.read')?await api('/operations/employees'):[];
  const fields=[['started_at','出発','datetime-local'],['ended_at','終了','datetime-local'],['start_odometer','開始距離 km','number'],['end_odometer','終了距離 km','number'],['purpose','用途','textarea'],...(operationsCan('incident.read')?[['dispatch_id','関連出動','select',operationsOptions(dispatches,'dispatch_id',d=>d.label)]]:[]),...(operationsCan('incident.crew.read')?[['driver_employee_id','運転者','select',operationsOptions(employees,'employee_id',e=>e.display_name)]]:[]),...(operationsCan('document.read')?[['document_id','原本ID（任意）']]:[])];
  operationsForm('運行登録',fields,{start_odometer:v.odometer},async values=>{await api('/operations/vehicles/'+v.vehicle_id+'/trips',operationsJSON('POST',{expected_version:v.version,...values}));await operationsVehicleDetail(v.vehicle_id)},()=>operationsVehicleDetail(v.vehicle_id));
}
async function operationsFuelForm(v){
  const fields=[['kind','区分','select',[['receipt','車両割当在庫の受入'],['issue','割当在庫から払出'],['refuel','外部給油（割当在庫増減なし）']]],['liters','量 L','number'],['amount','購入費 / 払出評価額（払出は参考値）','number'],['occurred_at','日時','datetime-local'],['notes','記録','textarea'],...(operationsCan('document.read')?[['document_id','伝票原本ID（任意）']]:[])];
  operationsForm('燃料登録',fields,{amount:0},async values=>{await api('/operations/vehicles/'+v.vehicle_id+'/fuel',operationsJSON('POST',{expected_version:v.version,...values}));await operationsVehicleDetail(v.vehicle_id)},()=>operationsVehicleDetail(v.vehicle_id));
}
async function operationsServiceForm(v){
  const faults=(await api('/operations/vehicles/'+v.vehicle_id+'/history')).services.filter(s=>s.kind==='fault'&&s.status!=='cancelled'&&!s.resolved_by_service_id);
  const fields=[['kind','区分','select',[['inspection','点検'],['vehicle_inspection','車検'],['repair','修理'],['fault','故障'],['service','整備']]],['resolves_fault_id','修理で解消する故障（該当する場合）','select',operationsOptions(faults,'service_id',s=>s.performed_on+' / '+s.description)],['performed_on','実施日','date'],['description','内容','textarea'],['cost','費用','number'],['next_inspection_on','次回点検・車検日','date'],['next_service_on','次回整備日','date'],['next_service_odometer','次回整備距離 km','number'],...(operationsCan('document.read')?[['document_id','原本ID（任意）']]:[])];
  operationsForm('点検・整備草案',fields,{cost:0},async values=>{await api('/operations/vehicles/'+v.vehicle_id+'/services',operationsJSON('POST',{expected_version:v.version,...values}));await operationsVehicleDetail(v.vehicle_id)},()=>operationsVehicleDetail(v.vehicle_id));
}
async function operationsAlerts(){const rows=await api('/operations/alerts');$('operationsContent').innerHTML='<h2>30日以内の期限・走行距離超過・未解消故障</h2>'+operationsHistoryTable(rows,['code','kind','due_on','days_remaining','due_odometer','description']);}
async function operationsSummary(){
  $('operationsContent').innerHTML='<h2>月次・年次集計</h2><div class="toolbar"><label>年<input id="operationsYear" type="number" min="1900" max="9998"></label><label>月（空欄は年次）<input id="operationsMonth" type="number" min="1" max="12"></label><button class="btn" id="operationsAggregate">集計</button></div><div id="operationsStats"></div>';
  $('operationsYear').value=new Date().getFullYear();operationsBind('operationsAggregate',async()=>{const q=new URLSearchParams({year:$('operationsYear').value});if($('operationsMonth').value)q.set('month',$('operationsMonth').value);let html='';for(const [permission,path,label] of [['incident.aggregate','statistics','事案・出動'],['fleet.aggregate','fleet-statistics','車両運用']]){if(!operationsCan(permission))continue;const r=await api('/operations/'+path+'?'+q);html+=`<h3>${label}</h3>${path==='fleet-statistics'?`<p>燃料購入費（受入・外部給油） ${esc(r.fuel_purchase_expense)} / 払出評価額（参考、購入費に含めません） ${esc(r.fuel_issue_valuation)}</p>`:''}<pre>${esc(JSON.stringify(r,null,2))}</pre>`}$('operationsStats').innerHTML=html||'<p>集計権限が必要です。</p>'});
}
async function operationsDownload(url){const r=await fetch(url);if(!r.ok){let body={};try{body=await r.json()}catch{}throw new Error(body.detail??'出力できません')}const blob=await r.blob();const objectURL=URL.createObjectURL(blob);const link=document.createElement('a');link.href=objectURL;link.download=r.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]??'operations-export.csv';document.body.append(link);link.click();link.remove();URL.revokeObjectURL(objectURL)}
async function operationsExchange(){
  const datasets=[['incidents','事案','incident'],['dispatches','出動','incident'],['vehicles','車両','fleet'],['trips','運行','fleet'],['fuel','燃料','fleet'],['services','点検・整備','fleet'],...(operationsCan('incident.crew.read')&&operationsCan('incident.crew.manage')?[['crew','隊員','incident']]:[])];
  const imports=datasets.filter(([, ,domain])=>operationsCan(domain+'.import')&&operationsCan(domain+'.create')&&operationsCan(domain+'.read'));
  const exports=[...datasets.map(([key,label,domain])=>[key,label,domain]),['summary','事案月次・年次','incident'],['fleet-summary','車両月次・年次','fleet'],...(operationsCan('incident.crew.read')?[['crew','隊員詳細','incident']]:[])].filter(([key,,domain])=>operationsCan(domain+'.export')&&operationsCan(domain+(['summary','fleet-summary'].includes(key)?'.aggregate':'.read')));
  $('operationsContent').innerHTML=`<h2>CSV・XLSX取込 / 出力</h2><p class="notice">取込はプレビュー後に明示的に確定します。確認済み・正式承認状態を取り込むことはできません。テンプレートの列名を使用し、関連ID・expected_versionを指定してください。</p><div class="toolbar"><label>取込対象<select id="operationsImportDataset">${imports.map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select></label><button class="btn" id="operationsImportTemplate">CSVテンプレート</button><label>ファイル<input id="operationsImportFile" type="file" accept=".csv,.xlsx"></label><button class="btn" id="operationsImportPreview">プレビュー</button></div><div id="operationsPreview"></div><hr><div class="toolbar"><label>出力対象<select id="operationsExportDataset">${exports.map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select></label><label>形式<select id="operationsExportFormat"><option value="csv">CSV</option><option value="xlsx">XLSX</option></select></label><label>集計年<input id="operationsExportYear" type="number" value="${new Date().getFullYear()}"></label><label>集計月<input id="operationsExportMonth" type="number" min="1" max="12"></label><button class="btn" id="operationsExport">出力</button></div>`;
  $('operationsImportPreview').disabled=!imports.length;$('operationsImportTemplate').disabled=!imports.length;$('operationsExport').disabled=!exports.length;
  operationsBind('operationsImportTemplate',()=>operationsDownload('/operations/import-template/'+$('operationsImportDataset').value));
  operationsBind('operationsImportPreview',async()=>{const file=$('operationsImportFile').files[0];if(!file)throw new Error('ファイルを選択してください');const body=new FormData();body.append('file',file);const p=await api('/operations/import/'+$('operationsImportDataset').value,{method:'POST',body});$('operationsPreview').innerHTML=`<p>${p.rows}行 / ファイルSHA256 ${esc(p.file_sha256)} / 有効期限 ${esc(p.expires_at)}</p><pre>${esc(JSON.stringify(p.sample,null,2))}</pre><button class="btn primary" id="operationsImportConfirm">確認して全行を取り込む</button>`;operationsBind('operationsImportConfirm',async()=>{const r=await api('/operations/import-previews/'+p.preview_id+'/confirm',operationsJSON('POST',{expected_version:p.version,file_sha256:p.file_sha256}));$('operationsPreview').textContent=`取込完了 ${r.inserted}行 / 元ファイルSHA256 ${r.file_sha256}`})});
  operationsBind('operationsExport',()=>{const q=new URLSearchParams({format:$('operationsExportFormat').value,year:$('operationsExportYear').value});if($('operationsExportMonth').value)q.set('month',$('operationsExportMonth').value);return operationsDownload('/operations/export/'+$('operationsExportDataset').value+'?'+q)});
}
