'use strict';
const el=id=>document.getElementById(id);const message=text=>{el('message').textContent=text;};
function clear(){el('loginForm').reset();el('renewForm').reset();el('account').textContent='';el('renewSection').hidden=true;el('loginSection').hidden=false;el('businessLink').hidden=true;}
async function request(path,body){const response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok){if(response.status===401||response.status===403)clear();throw new Error(response.status===401?'本人確認が必要です。ログインIDと現在のパスワードを確認してください。':typeof result.detail==='string'?result.detail:result.detail?.message||'入力内容とアカウント状態を確認してください。');}return result;}
function show(user){el('loginSection').hidden=true;el('renewSection').hidden=false;el('account').textContent=user.username;el('businessLink').hidden=user.password_change_required;message(user.password_change_required?'期限切れです。現在のパスワードで本人確認し、新しいパスワードへ更新してください。':'パスワードを更新できます。');}
el('loginForm').addEventListener('submit',async event=>{event.preventDefault();try{show(await request('/auth/login',Object.fromEntries(new FormData(event.target))));}catch(error){message(error.message);}finally{event.target.reset();}});
el('renewForm').addEventListener('submit',async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.target));if(data.new_password!==data.confirmation)throw new Error('新しいパスワードと確認が一致しません。');await request('/administration/password',{current_password:data.current_password,new_password:data.new_password});clear();message('更新しました。新しいパスワードでログインしてください。');}catch(error){message(error.message);}finally{event.target.reset();}});
el('logoutButton').addEventListener('click',async()=>{try{await request('/auth/logout',{});clear();message('ログアウトしました。');}catch(error){message(error.message);}});
request('/auth/me').then(show).catch(error=>message(error.message));
