'use strict';
const state={roles:[],rules:[],grants:[],permissions:[],accounts:[],staff:[],organizations:[],sources:new Map(),canManage:false,editor:null};
let generation=0;
class StaleRequest extends Error{}
const el=id=>document.getElementById(id),message=text=>{el('message').textContent=text;};
function clearSensitive(){generation++;for(const key of ['roles','rules','grants','permissions','accounts','staff','organizations'])state[key]=[];state.sources.clear();state.canManage=false;state.editor=null;for(const form of document.querySelectorAll('form'))form.reset();for(const id of ['ownRoles','ownPermissions','identity'])el(id).textContent='';for(const id of ['roleList','ruleList','grantList','permissionChoices','roleEdit','accountSelect','principalSelect','organizationSelect'])el(id).replaceChildren();for(const node of document.querySelectorAll('.sourceEvidence,.roleSelect'))node.replaceChildren();el('workspace').hidden=true;el('manager').hidden=true;el('loginSection').hidden=false;}
function clearManagement(){generation++;state.canManage=false;state.editor=null;for(const key of ['roles','rules','grants','permissions','accounts','staff','organizations'])state[key]=[];state.sources.clear();for(const id of ['roleForm','ruleForm','grantForm'])el(id).reset();for(const id of ['roleList','ruleList','grantList','permissionChoices','roleEdit','accountSelect','principalSelect','organizationSelect'])el(id).replaceChildren();for(const node of document.querySelectorAll('.sourceEvidence,.roleSelect'))node.replaceChildren();el('manager').hidden=true;}
function report(error){if(!(error instanceof StaleRequest))message(error.message);}
async function request(path,method='GET',body){const current=generation,response=await fetch(path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(current!==generation)throw new StaleRequest();if(!response.ok){if(response.status===401||response.status===403)clearSensitive();throw new Error(response.status===409?'版・状態・原本が変わりました。再読込して確認してください。':typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));}return result;}
const values=form=>Object.fromEntries(new FormData(form));
function options(node,rows,key,label,empty){const previous=node.value;node.replaceChildren();if(empty!==undefined)node.append(new Option(empty,''));for(const row of rows)node.append(new Option(label(row),row[key]));if([...node.options].some(x=>x.value===previous))node.value=previous;}
const roleName=id=>state.roles.find(x=>x.role_id===id)?.name||id;
function cell(row,text){const td=document.createElement('td');td.textContent=String(text??'');row.append(td);return td;}
function action(node,label,callback){const button=document.createElement('button');button.textContent=label;button.addEventListener('click',()=>callback().catch(report));node.append(button);}
function evidence(node,item){if(!item.source_document_id)return;const link=document.createElement('a');link.textContent='原本 '+item.source_sha256;link.href='/documents/'+encodeURIComponent(item.source_document_id)+'/download';node.append(document.createElement('br'),link);}
async function mutation(path,method,body,description){const why=body.reason?.trim();if(!why)throw new Error('Human確認理由を入力してください。');body.reason=why;if(!window.confirm(description+'\n理由: '+why))return false;await request(path,method,body);await refresh();message('Human確認を保存しました。変更対象者は再ログインが必要です。');return true;}
function editRole(){const form=el('roleForm'),row=state.roles.find(x=>x.role_id===el('roleEdit').value);state.editor=row?{role_id:row.role_id,version:row.version}:null;form.elements.name.value=row?.name||'';form.elements.active.checked=row?.active??true;form.elements.sensitive_acknowledged.checked=false;for(const input of el('permissionChoices').querySelectorAll('input'))input.checked=!!row?.permission_codes.includes(input.value);}
function render(){options(el('roleEdit'),state.roles.filter(x=>!x.system_role),'role_id',x=>x.name+' / v'+x.version,'新規Role');if(state.editor&&!state.roles.some(x=>x.role_id===state.editor.role_id)){el('roleEdit').append(new Option('編集中 '+el('roleForm').elements.name.value+' / v'+state.editor.version,state.editor.role_id));el('roleEdit').value=state.editor.role_id;}for(const node of document.querySelectorAll('.roleSelect'))options(node,state.roles.filter(x=>x.active&&x.code!=='system_admin'),'role_id',x=>x.name);el('roleList').replaceChildren();for(const role of state.roles){const p=document.createElement('p');p.textContent=role.name+' / '+(role.system_role?'システム定義・読取専用':'本部定義')+' / '+(role.active?'有効':'無効')+' / '+role.permission_codes.join('、');el('roleList').append(p);}options(el('accountSelect'),state.accounts.filter(x=>x.active),'user_id',x=>x.username);options(el('principalSelect'),state.staff.filter(x=>x.active),'employee_id',x=>x.display_name,'代理なし');options(el('organizationSelect'),state.organizations.filter(x=>x.active),'organization_id',x=>x.name,'指定なし');
 el('ruleList').replaceChildren();for(const item of state.rules){const row=document.createElement('tr');cell(row,item.name+' / '+roleName(item.role_id)+'\n'+(state.organizations.find(x=>x.organization_id===item.organization_id)?.name||item.organization_id||'所属指定なし')+' / '+(item.title||'役職指定なし')+' / '+(item.kind||'種別指定なし'));const proof=cell(row,item.valid_from+'〜'+(item.valid_to||'期限なし'));evidence(proof,item);const last=cell(row,item.active?'有効':'無効');action(last,item.active?'停止':'再有効化',async()=>{const reason=window.prompt('Human確認理由');if(reason===null)return;const sensitive=state.roles.find(x=>x.role_id===item.role_id)?.permission_codes.some(code=>state.permissions.find(p=>p.code===code)?.sensitive);const ack=!item.active&&sensitive?window.confirm('このRoleの機微権限を確認しましたか？'):false;await mutation('/administration/role-rules/'+item.rule_id,'PATCH',{expected_version:item.version,active:!item.active,sensitive_acknowledged:ack,reason},'Rule状態を変更しますか？');});el('ruleList').append(row);}
 el('grantList').replaceChildren();for(const item of state.grants){const row=document.createElement('tr');cell(row,(state.accounts.find(x=>x.user_id===item.user_id)?.username||item.user_id)+' / '+roleName(item.role_id)+'\n代理元: '+(state.staff.find(x=>x.employee_id===item.acting_for_employee_id)?.display_name||item.acting_for_employee_id||'なし'));const proof=cell(row,item.valid_from+'〜'+item.valid_to);evidence(proof,item);const last=cell(row,item.revoked_at?'取消済み: '+item.revocation_reason:'登録済み（有効期間・所属状態に従う）');if(!item.revoked_at)action(last,'取消',async()=>{const reason=window.prompt('Human取消理由');if(reason!==null)await mutation('/administration/role-grants/'+item.grant_id+'/revoke','POST',{expected_version:item.version,reason},'期限付き付与を取り消しますか？');});el('grantList').append(row);}
 for(const [key,id] of [['roles','rolesNext'],['rules','rulesNext'],['grants','grantsNext']])el(id).disabled=state[key].length%100!==0;
}
async function refresh(){const own=await request('/administration/own-role-explanation');el('identity').textContent=own.username+' / 業務日 '+own.business_date;const origins={permanent:'永続付与',appointment:'辞令',human_rule:'所属・役職Rule',temporary:'期限付き',acting:'代理'};el('ownRoles').textContent=own.roles.map(x=>x.name+' / '+(origins[x.origin]||x.origin)+(x.valid_from?' / '+x.valid_from+'〜'+(x.valid_to||'期限なし'):'')).join('\n')||'有効Roleなし';el('ownPermissions').textContent=own.permissions.map(x=>x.code+' / '+(x.description||'')).join('\n')||'付与権限なし';if(!own.permissions.some(x=>x.code==='account.manage')){clearManagement();return;}
 if(!state.canManage)await loadManagement(own.permissions.map(x=>x.code));state.canManage=true;el('manager').hidden=false;
 [state.roles,state.rules,state.grants,state.accounts,state.staff]=await Promise.all([request('/administration/permission-roles'),request('/administration/role-rules'),request('/administration/role-grants'),request('/administration/accounts'),request('/administration/account-staff')]);render();}
async function loadManagement(codes){state.permissions=await request('/administration/permissions');const legend=document.createElement('legend');legend.textContent='許可する業務権限';el('permissionChoices').append(legend);for(const permission of state.permissions){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=permission.code;input.name='permission_codes';label.append(input,document.createTextNode(permission.code+' '+(permission.description||'')+(permission.sensitive?' [機微]':'')));el('permissionChoices').append(label);}if(codes.includes('personnel.read'))state.organizations=await request('/administration/organizations');}
async function start(){clearSensitive();try{const context=await request('/administration/context');state.canManage=context.permissions.includes('account.manage');el('workspace').hidden=false;el('loginSection').hidden=true;el('manager').hidden=!state.canManage;if(state.canManage)await loadManagement(context.permissions);await refresh();message(context.username+' / 権限の根拠を確認してください。');}catch(error){report(error);}}
el('loginForm').addEventListener('submit',async event=>{event.preventDefault();const body=values(event.target);event.target.reset();try{await request('/auth/login','POST',body);await start();}catch(error){report(error);}});
el('logoutButton').addEventListener('click',async()=>{clearSensitive();try{await request('/auth/logout','POST');message('ログアウトしました。');}catch(error){report(error);}});el('refreshButton').addEventListener('click',()=>refresh().catch(report));el('roleEdit').addEventListener('change',editRole);
el('roleForm').addEventListener('submit',async event=>{event.preventDefault();try{const form=event.target,data=values(form),row=state.editor,body={name:data.name,active:data.active==='on',permission_codes:[...el('permissionChoices').querySelectorAll('input:checked')].map(x=>x.value),sensitive_acknowledged:data.sensitive_acknowledged==='on',reason:data.reason};if(row){body.expected_version=row.version;body.active=data.active==='on';}if(await mutation('/administration/permission-roles'+(row?'/'+row.role_id:''),row?'PATCH':'POST',body,'選択した権限をRoleとして正式保存しますか？')){form.reset();el('roleEdit').value='';editRole();}}catch(error){report(error);}});
function sourceIdentity(link){const url=new URL(link,location.origin);if(url.origin!==location.origin||url.search||url.hash)throw new Error('同じサーバーの原本リンクを指定してください。');const match=url.pathname.match(/^\/documents\/([0-9a-f-]{36})(?:\/download)?$/i);if(!match)throw new Error('原本リンクの形式を確認してください。');return match[1];}
for(const form of [el('ruleForm'),el('grantForm')]){form.elements.source_link.addEventListener('input',()=>{state.sources.delete(form.id);form.querySelector('.sourceEvidence').textContent='';});form.querySelector('.sourcePreview').addEventListener('click',async()=>{try{const link=form.elements.source_link.value.trim(),id=sourceIdentity(link),source=await request('/documents/'+id);if(form.elements.source_link.value.trim()!==link)return;state.sources.set(form.id,{link,source_document_id:id,expected_source_sha256:source.sha256});form.querySelector('.sourceEvidence').textContent=source.original_filename+' / SHA256 '+source.sha256;}catch(error){state.sources.delete(form.id);form.querySelector('.sourceEvidence').textContent='';report(error);}});form.addEventListener('submit',async event=>{event.preventDefault();try{const data=values(form),body={role_id:data.role_id,valid_from:data.valid_from,valid_to:data.valid_to||null,sensitive_acknowledged:data.sensitive_acknowledged==='on',reason:data.reason};if(form.id==='ruleForm'){body.name=data.name;body.organization_id=data.organization_id||null;body.title=data.title||null;body.kind=data.kind||null;}else{body.user_id=data.user_id;body.acting_for_employee_id=data.acting_for_employee_id||null;}if(data.source_link.trim()){const source=state.sources.get(form.id);if(!source||source.link!==data.source_link.trim())throw new Error('原本を照合してhashを確認してください。');body.source_document_id=source.source_document_id;body.expected_source_sha256=source.expected_source_sha256;}if(await mutation('/administration/'+(form.id==='ruleForm'?'role-rules':'role-grants'),'POST',body,'対象・期間・権限・根拠を確認して正式登録しますか？')){form.reset();state.sources.delete(form.id);form.querySelector('.sourceEvidence').textContent='';}}catch(error){report(error);}});}
for(const [key,id,path] of [['roles','rolesNext','permission-roles'],['rules','rulesNext','role-rules'],['grants','grantsNext','role-grants']])el(id).addEventListener('click',async()=>{try{const rows=await request('/administration/'+path+'?offset='+state[key].length);state[key].push(...rows);render();el(id).disabled=rows.length<100;}catch(error){report(error);}});
start();
