"""Formal cases remain independent of inspection observations and AI candidates."""
from sqlalchemy import BigInteger,Boolean,UniqueConstraint,CheckConstraint,Date,DateTime,ForeignKey,JSON,String,Text,Uuid
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
from .models import uuid_str,now_utc

class ViolationCase(Base):
    __tablename__='violation_cases'
    __table_args__=(CheckConstraint("status IN ('candidate','reviewed','confirmed','completed','resolved_candidate','withdrawn','superseded')",name='violation_case_status'),CheckConstraint("origin IN ('human','ai')",name='violation_case_origin'),CheckConstraint('version >= 1',name='violation_case_version'),)
    case_id:Mapped[str]=mapped_column(Uuid(as_uuid=False),primary_key=True,default=uuid_str)
    building_id:Mapped[str]=mapped_column(ForeignKey('facilities.building_id'),nullable=False,index=True)
    finding_id:Mapped[str|None]=mapped_column(ForeignKey('inspection_findings.finding_id'))
    supersedes_case_id:Mapped[str|None]=mapped_column(ForeignKey('violation_cases.case_id'))
    observed_on:Mapped[object]=mapped_column(Date,nullable=False)
    possible_issue:Mapped[str]=mapped_column(Text,nullable=False)
    missing_information:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    confirmation_steps:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    rule_version_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    evidence_document_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    procedure_document_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    origin:Mapped[str]=mapped_column(String(20),nullable=False,default='human')
    ai_provenance:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default='candidate',index=True)
    review_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    reviewed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    reviewed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    confirmed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    confirmed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    last_human_reason:Mapped[str|None]=mapped_column(Text)
    created_by:Mapped[str]=mapped_column(ForeignKey('app_users.user_id'),nullable=False)
    created_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    updated_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    version:Mapped[int]=mapped_column(BigInteger,nullable=False,default=1)
    completed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    completed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))

class ViolationMeasure(Base):
    __tablename__='violation_measures'
    __table_args__=(CheckConstraint("kind IN ('guidance','order','disposition')",name='violation_measure_kind'),CheckConstraint("status IN ('draft','reviewed','confirmed','cancelled','withdrawn')",name='violation_measure_status'),)
    measure_id:Mapped[str]=mapped_column(Uuid(as_uuid=False),primary_key=True,default=uuid_str)
    case_id:Mapped[str]=mapped_column(ForeignKey('violation_cases.case_id'),nullable=False,index=True)
    kind:Mapped[str]=mapped_column(String(30),nullable=False)
    instruction:Mapped[str]=mapped_column(Text,nullable=False)
    official_reference:Mapped[str|None]=mapped_column(String(400))
    due_on:Mapped[object|None]=mapped_column(Date)
    document_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    procedure_document_ids:Mapped[list]=mapped_column(JSON,nullable=False,default=list)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default='draft')
    review_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    reviewed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    reviewed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    confirmed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    confirmed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    withdrawal_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    last_human_reason:Mapped[str|None]=mapped_column(Text)
    created_by:Mapped[str]=mapped_column(ForeignKey('app_users.user_id'),nullable=False)
    created_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    updated_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    version:Mapped[int]=mapped_column(BigInteger,nullable=False,default=1)

class CorrectiveAction(Base):
    __tablename__='corrective_actions'
    __table_args__=(CheckConstraint("status IN ('open','responded','verified','completed','cancelled')",name='corrective_action_status'),)
    action_id:Mapped[str]=mapped_column(Uuid(as_uuid=False),primary_key=True,default=uuid_str)
    case_id:Mapped[str]=mapped_column(ForeignKey('violation_cases.case_id'),nullable=False,index=True)
    measure_id:Mapped[str|None]=mapped_column(ForeignKey('violation_measures.measure_id'))
    description:Mapped[str]=mapped_column(Text,nullable=False)
    due_on:Mapped[object|None]=mapped_column(Date,index=True)
    status:Mapped[str]=mapped_column(String(30),nullable=False,default='open')
    verification_passed:Mapped[bool|None]=mapped_column(Boolean)
    verification_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    verified_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    verified_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    completed_by:Mapped[str|None]=mapped_column(ForeignKey('app_users.user_id'))
    completed_at:Mapped[object|None]=mapped_column(DateTime(timezone=True))
    completion_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    created_by:Mapped[str]=mapped_column(ForeignKey('app_users.user_id'),nullable=False)
    created_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    updated_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
    version:Mapped[int]=mapped_column(BigInteger,nullable=False,default=1)

class CorrectionEvent(Base):
    __tablename__='correction_events'
    __table_args__=(UniqueConstraint('action_id','sequence_no',name='correction_event_sequence'),CheckConstraint("kind IN ('instruction','response','verification','completion','cancel','reopen')",name='correction_event_kind'))
    event_id:Mapped[str]=mapped_column(Uuid(as_uuid=False),primary_key=True,default=uuid_str)
    action_id:Mapped[str]=mapped_column(ForeignKey('corrective_actions.action_id'),nullable=False,index=True)
    sequence_no:Mapped[int]=mapped_column(BigInteger,nullable=False)
    kind:Mapped[str]=mapped_column(String(30),nullable=False)
    text:Mapped[str]=mapped_column(Text,nullable=False)
    human_reason:Mapped[str]=mapped_column(Text,nullable=False)
    verification_passed:Mapped[bool|None]=mapped_column(Boolean)
    source_snapshot:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    created_by:Mapped[str]=mapped_column(ForeignKey('app_users.user_id'),nullable=False)
    created_at:Mapped[object]=mapped_column(DateTime(timezone=True),default=now_utc)
